const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { PGlite } = require(process.env.BALC_PGLITE_PATH || path.join(os.tmpdir(),'balc-sql-test/node_modules/@electric-sql/pglite'));
test('PostgreSQL migration, room membership, private state, atomic actions and replay', async () => {
    const db=new PGlite();
    try {
        await db.exec(`create role anon; create role authenticated; create schema auth; create schema realtime;
        create table auth.users(id uuid primary key);
        create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
        create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('is_anonymous',coalesce(nullif(current_setting('test.anonymous',true),''),'false')::boolean) $$;
        create table realtime.messages(extension text);
        create function realtime.topic() returns text language sql stable as $$ select current_setting('test.topic',true) $$;
        alter table realtime.messages enable row level security;
        grant usage on schema auth,realtime to authenticated;
        grant select,insert on realtime.messages to authenticated;
        create publication supabase_realtime;`);
        await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/battle-online.sql'),'utf8'));
        const ids=['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003'];
        for(const id of ids) await db.query('insert into auth.users values($1)',[id]);
        const as=async(i)=>{await db.exec('reset role'); await db.query("select set_config('test.uid',$1,false)",[ids[i]]); await db.exec('set role authenticated');};
        const one=async(sql,args=[]) => (await db.query(sql,args)).rows[0];
        await as(0);
        const r=(await one("select public.balc_create_room('{}') as r")).r;
        assert.match(r.code,/^[0-9]{6}$/);
        await assert.rejects(db.query("update public.battle_rooms set revision=999"),/permission denied/);
        await as(1);
        assert.equal((await db.query('select * from public.battle_rooms')).rows.length,0);
        const joined=(await one("select public.balc_join_room($1,'{}') as r",[r.code])).r;
        assert.equal(joined.guest_id,ids[1]);
        await as(2);
        assert.equal((await one("select public.balc_join_room($1,'{}') as r",[r.code])).r.error,'ROOM_NOT_FOUND');
        assert.equal((await db.query('select * from public.battle_rooms')).rows.length,0);
        await as(0);
        let snapshot={currentTurn:'player',gameEnded:false,secret:'host checkpoint'};
        let commit=await one('select public.balc_commit($1,0,null,$2,$3,$4) as revision',[r.id,snapshot,{own:'host'},{own:'guest'}]);
        assert.equal(commit.revision,1);
        await as(1);
        assert.equal((await db.query('select * from public.battle_checkpoints')).rows.length,0);
        assert.deepEqual((await one('select payload from public.battle_views')).payload,{own:'guest'});
        await assert.rejects(db.query('select public.balc_commit($1,1,null,$2,$3,$4)',[r.id,snapshot,{},{}]),/HOST_REQUIRED/);
        const req='10000000-0000-4000-8000-000000000001';
        const action={name:'playerEndTurn',args:[]};
        await assert.rejects(db.query('select public.balc_submit_action($1,$2,1,$3)',[r.id,req,action]),/NOT_YOUR_TURN/);
        await as(0);
        await db.query('select public.balc_submit_action($1,$2,1,$3)',[r.id,req,action]);
        await db.query('select public.balc_submit_action($1,$2,1,$3)',[r.id,req,action]);
        assert.equal((await db.query('select * from public.battle_match_actions')).rows.length,1);
        await assert.rejects(db.query('select public.balc_submit_action($1,$2,1,$3)',[r.id,req,{name:'other',args:[]}]),/REQUEST_REUSED/);
        await assert.rejects(db.query('select public.balc_submit_action($1,$2,1,$3)',[r.id,'10000000-0000-4000-8000-000000000002',action]),/unique constraint/);
        snapshot={currentTurn:'cpu',gameEnded:false};
        await db.query('select public.balc_commit($1,1,$2,$3,$4,$5)',[r.id,req,snapshot,{},{}]);
        await assert.rejects(db.query('select public.balc_commit($1,1,$2,$3,$4,$5)',[r.id,req,snapshot,{},{}]),/STALE_REVISION/);
        assert.equal((await one('select public.balc_submit_action($1,$2,1,$3) as r',[r.id,req,action])).r.processed,true);
        await as(1);
        await db.query('select public.balc_submit_action($1,$2,2,$3)',[r.id,'10000000-0000-4000-8000-000000000003',action]);
        await db.query("select set_config('test.topic',$1,false)",[`balc:${r.id}`]);
        await db.query("insert into realtime.messages values('presence')");
        await as(2);
        assert.equal((await db.query('select * from realtime.messages')).rows.length,0);
        await assert.rejects(db.query("insert into realtime.messages values('presence')"),/row-level security/);
        for(let i=0;i<20;i++) await db.query("select public.balc_join_room('999999','{}')");
        assert.equal((await one("select public.balc_join_room('999999','{}') as r")).r.error,'RATE_LIMIT');
        await db.query("select set_config('test.anonymous','true',false)");
        await assert.rejects(db.query("select public.balc_create_room('{}')"),/LOGIN_REQUIRED/);
        await db.query("select set_config('test.anonymous','false',false)");
        await as(1);
        await db.query('select public.balc_leave_room($1)',[r.id]);
        assert.equal((await one('select status from public.battle_rooms')).status,'closed');
    } finally { await db.close(); }
});
