// 台本原本: docs/story/episode9-scenario.md（修正一覧を適用し、表示台詞の行末句点だけ除去）
// 敗北会話: docs/story/lose-lines-ep9.md（2026-10-03 オーナー承認済み）
window.BattleStoryData.register({
    "id": "episode9",
    "number": 9,
    "title": "六人でやれば",
    "protagonist": "chizuru",
    "unlockRequires": "episode8",
    "summary": "昼を過ぎて大忙しの教室。人手が足りなくなった千鶴を、六人みんなで支えることに――。",
    "defaultPositions": {
        "chizuru": "right",
        "kanna": "left",
        "mai": "left",
        "takumi": "left",
        "akatsuki": "right",
        "tsuyoshi": "left",
        "classmate2": "left",
        "classmate1": "left"
    },
    "scenes": [
        {
            "id": "scene1",
            "background": "festival-kitchen",
            "bgm": "story",
            "lines": [
                {"id":"scene1-001","speaker":"narration","text":"","direction":"昼を過ぎ、教室は朝よりも混み始めている"},
                {"id":"scene1-002","speaker":"narration","text":"","direction":"注文が次々に入り、料理スペースも慌ただしい"},
                {"id":"scene1-003","speaker":"chizuru","position":"right","expression":"flustered","direction":"【右：千鶴／忙しそう】","text":"カレー二つ、キーマ一つ！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines",
                "se": "thud"},
                {"id":"scene1-004","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"こっちできたよ"},
                {"id":"scene1-005","speaker":"chizuru","position":"right","expression":"flustered","direction":"【右：千鶴】","text":"持ってくる！",
                "mark": "!"},
                {"id":"scene1-006","speaker":"narration","text":"","direction":"クラスメートの一人が少しふらつく"},
                {"id":"scene1-007","speaker":"classmate1","position":"left","expression":"sick","direction":"【左：クラスメート／具合が悪そう】","text":"ごめん、ちょっと気持ち悪いかも……"},
                {"id":"scene1-008","speaker":"chizuru","position":"right","expression":"worried","direction":"【右：千鶴／心配】","pose": "behind", "text":"大丈夫？"},
                {"id":"scene1-009","speaker":"kanna","position":"left","expression":"troubled","direction":"【左：栞那】","text":"顔色悪いよ"},
                {"id":"scene1-010","speaker":"classmate1","position":"left","expression":"sick","direction":"【クラスメート】","text":"少し休めば大丈夫だと思う"},
                {"id":"scene1-011","speaker":"chizuru","position":"right","expression":"worried","direction":"【右：千鶴】","text":"無理しないで"},
                {"id":"scene1-012","speaker":"kanna","position":"left","expression":"troubled","direction":"【栞那】","text":"保健室行ったほうがいいよ"},
                {"id":"scene1-013","speaker":"narration","text":"","direction":"別のクラスメートが近づく"},
                {"id":"scene1-014","speaker":"classmate2","position":"left","expression":"worried","direction":"【左：クラスメート2】","text":"私が連れてく"},
                {"id":"scene1-015","speaker":"classmate2","position":"left","expression":"smile","direction":"【クラスメート2】","text":"あとで代われる子も探してくるね"},
                {"id":"scene1-016","speaker":"chizuru","position":"right","expression":"worried","direction":"【右：千鶴】","text":"お願い"},
                {"id":"scene1-017","speaker":"narration","text":"","direction":"二人が料理スペースを離れる","hide":["classmate1","classmate2"]},
                {"id":"scene1-018","speaker":"narration","text":"","direction":"一気に人手が減る"},
                {"id":"scene1-019","speaker":"chizuru","position":"right","expression":"flustered","direction":"【右：千鶴／少し焦る】","pose": "default", "text":"……まずいかも",
                "motion": "tremble",
                "mark": "sweat"},
                {"id":"scene1-020","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"まずいね"},
                {"id":"scene1-021","speaker":"narration","text":"","direction":"教室側から声"},
                {"id":"scene1-022","speaker":"narration","name":"？？？","text":"すみませーん！","direction":"","offscreen":true},
                {"id":"scene1-023","speaker":"narration","text":"","direction":"さらに別の声"},
                {"id":"scene1-024","speaker":"narration","name":"？？？","text":"注文お願いしまーす！","direction":"","offscreen":true},
                {"id":"scene1-025","speaker":"chizuru","position":"right","expression":"flustered","direction":"【右：千鶴】","text":"私、注文行ってくる！",
                "mark": "!"},
                {"id":"scene1-026","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"千鶴"},
                {"id":"scene1-027","speaker":"chizuru","position":"right","expression":"flustered","direction":"【右：千鶴】","text":"なに？"},
                {"id":"scene1-028","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"料理もやる気でしょ"},
                {"id":"scene1-029","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"うん"},
                {"id":"scene1-030","speaker":"kanna","position":"left","expression":"exasperated","direction":"【栞那／少し呆れる】","text":"一人で何人分働くつもり？"},
                {"id":"scene1-031","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"できるだけ"},
                {"id":"scene1-032","speaker":"kanna","position":"left","expression":"exasperated","direction":"【栞那】","text":"それ答えになってない"}
            ]
        },
        {
            "id": "scene2",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                {"id":"scene2-001","speaker":"narration","text":"","direction":"舞依と拓海が状況に気付く"},
                {"id":"scene2-002","speaker":"takumi","position":"left","expression":"normal","direction":"【左：拓海】","text":"人、足りてない？"},
                {"id":"scene2-003","speaker":"chizuru","position":"right","expression":"worried","direction":"【右：千鶴】","pose": "behind", "text":"ちょっとだけ"},
                {"id":"scene2-004","speaker":"mai","position":"left","expression":"normal","direction":"【左：舞依】","text":"ちょっとじゃないでしょ"},
                {"id":"scene2-005","speaker":"chizuru","position":"right","expression":"worried","direction":"【右：千鶴】","text":"でも大丈夫"},
                {"id":"scene2-006","speaker":"mai","position":"left","expression":"cold","direction":"【舞依／少し冷たい】","text":"大丈夫じゃない人ほどそう言う"},
                {"id":"scene2-007","speaker":"chizuru","position":"right","expression":"worried","direction":"【千鶴】","text":"そう？"},
                {"id":"scene2-008","speaker":"mai","position":"left","expression":"cold","direction":"【舞依】","text":"そう"},
                {"id":"scene2-009","speaker":"takumi","position":"left","expression":"gentle","direction":"【拓海／柔らかく】","text":"僕たちもまだ手伝えるよ"},
                {"id":"scene2-010","speaker":"chizuru","position":"right","expression":"worried","direction":"【千鶴】","text":"でもずっと手伝ってもらってるし"},
                {"id":"scene2-011","speaker":"mai","position":"left","expression":"cold","direction":"【舞依】","text":"嫌なら帰ってる"},
                {"id":"scene2-012","speaker":"chizuru","position":"right","expression":"laugh","direction":"【千鶴／少し笑う】","text":"それはそうか"},
                {"id":"scene2-013","speaker":"narration","text":"","direction":"少し離れた席"},
                {"id":"scene2-014","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【左：剛】","text":"なんかめっちゃ忙しそうやな",
                "motion": "slideIn",
                "se": "swish"},
                {"id":"scene2-015","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【右：暁】","text":"見たら分かるやろ"},
                {"id":"scene2-016","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"俺らもなんかやろか？"},
                {"id":"scene2-017","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【右：暁】","text":"なんで俺まで入ってんねん"},
                {"id":"scene2-018","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"二人で来てんねんから二人でやるやろ！",
                "mark": "!"},
                {"id":"scene2-019","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"その理論雑やな"},
                {"id":"scene2-020","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"暇やろ？"},
                {"id":"scene2-021","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"……まあ"},
                {"id":"scene2-022","speaker":"narration","text":"","direction":"剛が千鶴たちのところへ行く"},
                {"id":"scene2-023","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【左：剛】","text":"なんか手伝おか？"},
                {"id":"scene2-024","speaker":"chizuru","position":"right","expression":"surprised","direction":"【右：千鶴／驚く】","text":"いいの？",
                "motion": "hop",
                "mark": "!",
                "se": "pop"},
                {"id":"scene2-025","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"ええで！",
                "mark": "!"},
                {"id":"scene2-026","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【右：暁／少し離れて】","text":"勝手に俺まで巻き込むなよ"},
                {"id":"scene2-027","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"でも来てるやん！",
                "mark": "!"},
                {"id":"scene2-028","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【右：暁】","text":"お前が勝手に話進めるからや"},
                {"id":"scene2-029","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴／笑顔】","pose": "default", "text":"じゃあ二人ともお願い！",
                "mark": "!"},
                {"id":"scene2-030","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"決定なん？"},
                {"id":"scene2-031","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","text":"嫌？"},
                {"id":"scene2-032","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"……別に"},
                {"id":"scene2-033","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴／笑顔】","text":"じゃあお願い！",
                "mark": "sparkle"},
                {"id":"scene2-034","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁／小声】","text":"断る隙ないやん"}
            ]
        },
        {
            "id": "scene3",
            "background": "festival-kitchen",
            "bgm": "story",
            "lines": [
                {"id":"scene3-001","speaker":"narration","text":"","direction":"役割分担"},
                {"id":"scene3-002","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"剛は注文と配膳お願い"},
                {"id":"scene3-003","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"任しとけ！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines",
                "se": "thud"},
                {"id":"scene3-004","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"声は少し抑えて"},
                {"id":"scene3-005","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"任しとけ"},
                {"id":"scene3-006","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"急に小さい"},
                {"id":"scene3-007","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"暁は皿洗いと片付け"},
                {"id":"scene3-008","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"地味やな"},
                {"id":"scene3-009","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"嫌なら剛と注文取る？"},
                {"id":"scene3-010","speaker":"narration","text":"","direction":"剛の大きな声が聞こえる"},
                {"id":"scene3-011","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"","text":"カレー二つ入りまーす！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines",
                "se": "thud"},
                {"id":"scene3-012","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"皿洗いでええわ"},
                {"id":"scene3-013","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"賢い"},
                {"id":"scene3-014","speaker":"takumi","position":"left","expression":"normal","direction":"【左：拓海】","text":"僕は注文まとめようか？"},
                {"id":"scene3-015","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"助かる"},
                {"id":"scene3-016","speaker":"mai","position":"left","expression":"normal", "pose": "behind","direction":"【左：舞依】","text":"私は？"},
                {"id":"scene3-017","speaker":"chizuru","position":"right","expression":"normal","direction":"【右：千鶴】","text":"舞依ちゃんは配膳お願い"},
                {"id":"scene3-018","speaker":"mai","position":"left","expression":"happy","direction":"【舞依／少し嬉しそう】","text":"千鶴ちゃんのお願いなら"},
                {"id":"scene3-019","speaker":"takumi","position":"left","expression":"laugh","direction":"【左：拓海／笑う】","text":"分かりやすいなあ"},
                {"id":"scene3-020","speaker":"mai","position":"left","expression":"serious", "pose": "default","direction":"【舞依】","text":"何か？"},
                {"id":"scene3-021","speaker":"takumi","position":"left","expression":"exasperated","direction":"【拓海】","text":"何でもない"}
            ]
        },
        {
            "id": "scene4",
            "background": "festival-kitchen",
            "bgm": "story",
            "lines": [
                {"id":"scene4-001","speaker":"narration","text":"","direction":"時間経過"},
                {"id":"scene4-002","speaker":"narration","text":"","direction":"剛が注文を取る"},
                {"id":"scene4-003","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【左：剛】","text":"カレー一つ、キーマ二つ！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines",
                "se": "thud"},
                {"id":"scene4-004","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁／皿洗い中】","text":"お前さっきキーマ三つ言うてなかった？"},
                {"id":"scene4-005","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"あれ？",
                "mark": "?"},
                {"id":"scene4-006","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁】","text":"注文票見ろや"},
                {"id":"scene4-007","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛／確認】","text":"あ、二つや！",
                "mark": "!"},
                {"id":"scene4-008","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"危な"},
                {"id":"scene4-009","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"助かったわ！",
                "mark": "!"},
                {"id":"scene4-010","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁】","text":"ちゃんと見ろ"},
                {"id":"scene4-011","speaker":"narration","text":"","direction":"千鶴が大量の皿を持ってくる"},
                {"id":"scene4-012","speaker":"chizuru","position":"right","expression":"normal","direction":"【右：千鶴】","text":"暁、これもお願い"},
                {"id":"scene4-013","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁／皿を見る】","text":"多ない？"},
                {"id":"scene4-014","speaker":"chizuru","position":"right","expression":"normal","direction":"【千鶴】","text":"多い"},
                {"id":"scene4-015","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"そこ認めるんや"},
                {"id":"scene4-016","speaker":"chizuru","position":"right","expression":"normal","direction":"【千鶴】","text":"暁、皿洗い上手だね"},
                {"id":"scene4-017","speaker":"akatsuki","position":"right","expression":"frozen","direction":"【暁／一瞬止まる】","text":"褒めるとこそこなん？",
                "motion": "tremble",
                "mark": "…",
                "se": "shock"},
                {"id":"scene4-018","speaker":"chizuru","position":"right","expression":"normal","direction":"【千鶴】","text":"うん"},
                {"id":"scene4-019","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"即答かい"},
                {"id":"scene4-020","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴／笑顔】","pose": "behind", "text":"助かってるよ"},
                {"id":"scene4-021","speaker":"akatsuki","position":"right","expression":"embarrassed","direction":"【暁／少し照れ隠し】","text":"……ほな早よ次持ってこい",
                "mark": "sweat"},
                {"id":"scene4-022","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","text":"まだあるよ"},
                {"id":"scene4-023","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"ほんまに持ってくるんかい"}
            ]
        },
        {
            "id": "scene5",
            "background": "festival-kitchen",
            "bgm": "story",
            "lines": [
                {"id":"scene5-001","speaker":"narration","text":"","direction":"さらに忙しくなる"},
                {"id":"scene5-002","speaker":"narration","text":"","direction":"千鶴が料理、配膳、片付けを同時にやろうとする"},
                {"id":"scene5-003","speaker":"chizuru","position":"right","expression":"flustered","direction":"【右：千鶴／焦り】","text":"これ運んで、そのあと注文取って……",
                "motion": "tremble",
                "mark": "sweat"},
                {"id":"scene5-004","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"千鶴"},
                {"id":"scene5-005","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"なに？"},
                {"id":"scene5-006","speaker":"kanna","position":"left","expression":"serious","direction":"【栞那／少し強め】","text":"全部やろうとしない",
                "motion": "zoom",
                "mark": "!"},
                {"id":"scene5-007","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"でも人足りないし"},
                {"id":"scene5-008","speaker":"mai","position":"left","expression":"normal","direction":"【舞依】","text":"私たちいるよ"},
                {"id":"scene5-009","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"でもこれは私たちのクラスの出し物だから"},
                {"id":"scene5-010","speaker":"takumi","position":"left","expression":"normal","direction":"【拓海】","text":"今さらそこ気にする？"},
                {"id":"scene5-011","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"だって……"},
                {"id":"scene5-012","speaker":"akatsuki","position":"right","expression":"serious","direction":"【右：暁】","text":"一人で全部やろうとすんなや",
                "motion": "zoom",
                "mark": "!"},
                {"id":"scene5-013","speaker":"narration","text":"","direction":"千鶴が暁を見る"},
                {"id":"scene5-014","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"でも"},
                {"id":"scene5-015","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁】","text":"でもちゃう"},
                {"id":"scene5-016","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁／少し強め】","text":"手ぇ空いてるやつおんねんから使え",
                "motion": "zoom",
                "mark": "!"},
                {"id":"scene5-017","speaker":"chizuru","position":"right","expression":"flustered","direction":"【千鶴】","text":"使えって"},
                {"id":"scene5-018","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"言い方は悪かった"},
                {"id":"scene5-019","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛／横から】","text":"使ってええで！"},
                {"id":"scene5-020","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"お前は元気やな"},
                {"id":"scene5-021","speaker":"kanna","position":"left","expression":"serious","direction":"【栞那】","text":"ほら"},
                {"id":"scene5-022","speaker":"kanna","position":"left","expression":"laugh","direction":"【栞那／少し笑う】","text":"たまには頼ったら？"},
                {"id":"scene5-023","speaker":"chizuru","position":"right","expression":"thinking","direction":"【千鶴／少し迷う】","text":"……"},
                {"id":"scene5-024","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","pose": "behind", "text":"じゃあお願い",
                "mark": "sparkle",
                "se": "idea"},
                {"id":"scene5-025","speaker":"mai","position":"left","expression":"smile","direction":"【舞依／笑顔】","text":"最初からそうして"},
                {"id":"scene5-026","speaker":"takumi","position":"left","expression":"smile","direction":"【拓海】","text":"任せて"},
                {"id":"scene5-027","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"よっしゃ！",
                "motion": "hop",
                "mark": "note",
                "se": "laugh"},
                {"id":"scene5-028","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"なんでお前が一番やる気あんねん"}
            ]
        },
        {
            "id": "scene6",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                {"id":"scene6-001","speaker":"narration","text":"","direction":"少し時間が経過"},
                {"id":"scene6-002","speaker":"narration","text":"","direction":"客足が落ち着く"},
                {"id":"scene6-003","speaker":"narration","text":"","direction":"全員少し疲れている"},
                {"id":"scene6-004","speaker":"tsuyoshi","position":"left","expression":"tired","direction":"【左：剛】","text":"終わった……"},
                {"id":"scene6-005","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"お前途中から声小さなってたで"},
                {"id":"scene6-006","speaker":"tsuyoshi","position":"left","expression":"tired","direction":"【剛】","text":"体力使い切った"},
                {"id":"scene6-007","speaker":"takumi","position":"left","expression":"laugh","direction":"【拓海／笑う】","text":"でも助かったよ"},
                {"id":"scene6-008","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"やろ？"},
                {"id":"scene6-009","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"調子乗んな"},
                {"id":"scene6-010","speaker":"chizuru","position":"right","expression":"happy","direction":"【右：千鶴／嬉しそう】","pose": "cheer", "text":"みんなありがとう！",
                "mark": "sparkle"},
                {"id":"scene6-011","speaker":"chizuru","position":"right","expression":"happy","direction":"【千鶴】","text":"ほんと助かった！",
                "mark": "!"},
                {"id":"scene6-012","speaker":"kanna","position":"left","expression":"smile","direction":"【栞那】","pose": "pocket", "text":"千鶴一人だったら倒れてたかもね"},
                {"id":"scene6-013","speaker":"chizuru","position":"right","expression":"happy","direction":"【千鶴】","text":"そこまでは"},
                {"id":"scene6-014","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"いや、やりかねん"},
                {"id":"scene6-015","speaker":"chizuru","position":"right","expression":"happy","direction":"【千鶴】","text":"暁まで"},
                {"id":"scene6-016","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"実績あるやろ"},
                {"id":"scene6-017","speaker":"chizuru","position":"right","expression":"pout","direction":"【千鶴／不満】","pose": "default", "text":"ない！",
                "mark": "!"},
                {"id":"scene6-018","speaker":"kanna","position":"left","expression":"smug","direction":"【栞那】","text":"ある"},
                {"id":"scene6-019","speaker":"chizuru","position":"right","expression":"pout","direction":"【千鶴】","text":"栞那まで！",
                "motion": "shake",
                "mark": "anger",
                "se": "thud"}
            ]
        },
        {
            "id": "scene7",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                {"id":"scene7-001","speaker":"narration","text":"","direction":"舞依がBattle à la carteのカードを見る"},
                {"id":"scene7-002","speaker":"mai","position":"left","expression":"smile", "pose": "behind","direction":"【左：舞依】","text":"千鶴ちゃん"},
                {"id":"scene7-003","speaker":"chizuru","position":"right","expression":"normal","direction":"【右：千鶴】","text":"ん？"},
                {"id":"scene7-004","speaker":"mai","position":"left","expression":"smile","direction":"【舞依】","text":"もう一回やらない？"},
                {"id":"scene7-005","speaker":"chizuru","position":"right","expression":"happy","direction":"【千鶴／少し嬉しそう】","text":"Battle à la carte？"},
                {"id":"scene7-006","speaker":"mai","position":"left","expression":"smile","direction":"【舞依】","text":"うん"},
                {"id":"scene7-007","speaker":"mai","position":"left","expression":"laugh", "pose": "default","direction":"【舞依／少し笑う】","text":"前は私が勝ったから"},
                {"id":"scene7-008","speaker":"chizuru","position":"right","expression":"pout","direction":"【千鶴／むっとする】","text":"覚えてる"},
                {"id":"scene7-009","speaker":"mai","position":"left","expression":"laugh","direction":"【舞依】","text":"じゃあリベンジする？"},
                {"id":"scene7-010","speaker":"chizuru","position":"right","expression":"pout","direction":"【千鶴】","text":"する！",
                "motion": "zoom",
                "mark": "!"},
                {"id":"scene7-011","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁／少し離れて】","text":"即答やな"},
                {"id":"scene7-012","speaker":"chizuru","position":"right","expression":"pout","direction":"【千鶴】","text":"負けたまま嫌だから！",
                "mark": "!"},
                {"id":"scene7-013","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／少し笑う】","text":"負けず嫌いやん"},
                {"id":"scene7-014","speaker":"chizuru","position":"right","expression":"pout","direction":"【千鶴】","text":"暁には言われたくない！",
                "mark": "!"},
                {"id":"scene7-015","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"俺なんも言うてへんやろ"},
                {
                    "id": "battle-start",
                    "speaker": "narration",
                    "text": "",
                    "direction": "BATTLE START",
                    "battle": true
                }
            ]
        },
        {
            "id": "win",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                {"id":"win-001","speaker":"chizuru","position":"right","expression":"happy","direction":"【右：千鶴／嬉しそう】","pose": "cheer", "text":"勝った！",
                "motion": "hop",
                "mark": "sparkle",
                "se": "sparkle"},
                {"id":"win-002","speaker":"mai","position":"left","expression":"sad", "pose": "behind","direction":"【左：舞依／少し悔しそう】","text":"負けた"},
                {"id":"win-003","speaker":"chizuru","position":"right","expression":"smug","direction":"【千鶴／得意げ】","text":"これで一勝一敗"},
                {"id":"win-004","speaker":"mai","position":"left","expression":"sad","direction":"【舞依】","text":"じゃあ次でもう一回"},
                {"id":"win-005","speaker":"chizuru","position":"right","expression":"smug","direction":"【千鶴】","text":"いいよ"},
                {"id":"win-006","speaker":"mai","position":"left","expression":"laugh", "pose": "default","direction":"【舞依／少し笑う】","text":"次は負けないから"},
                {"id":"win-007","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","pose": "default", "text":"私も"},
                {"id":"win-008","speaker":"takumi","position":"left","expression":"smile","direction":"【左：拓海／笑顔】","text":"二人とも楽しそうだね"},
                {"id":"win-009","speaker":"mai","position":"left","expression":"laugh", "pose": "cheer","direction":"【舞依】","text":"楽しいです"},
                {"id":"win-010","speaker":"chizuru","position":"right","expression":"smile","direction":"【右：千鶴】","text":"うん"},
                {"id":"win-011","speaker":"narration","text":"","direction":"少し離れたところ"},
                {"id":"win-012","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁／千鶴を見る】","text":"……"},
                {"id":"win-013","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【左：剛】","text":"何見てん？"},
                {"id":"win-014","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"別に"},
                {"id":"win-015","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"千鶴？"},
                {"id":"win-016","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁／すぐ返す】","text":"ちゃうわ",
                "mark": "sweat"},
                {"id":"win-017","speaker":"tsuyoshi","position":"left","expression":"laugh","direction":"【剛／笑う】","text":"名前出しただけやん",
                "motion": "hop",
                "mark": "note",
                "se": "laugh"},
                {"id":"win-018","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"うるさいねん"},
                {"id":"win-019","speaker":"narration","text":"","direction":"千鶴がこちらを見る"},
                {"id":"win-020","speaker":"chizuru","position":"right","expression":"smile","direction":"【右：千鶴／笑顔】","text":"暁"},
                {"id":"win-021","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"なんや"},
                {"id":"win-022","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","pose": "behind", "text":"さっきありがと"},
                {"id":"win-023","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"何が？"},
                {"id":"win-024","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","text":"手伝ってくれたの"},
                {"id":"win-025","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴／笑顔】","text":"皿洗いも"},
                {"id":"win-026","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁／呆れる】","text":"また皿洗い褒めんの？"},
                {"id":"win-027","speaker":"chizuru","position":"right","expression":"smile","direction":"【千鶴】","text":"上手だったから"},
                {"id":"win-028","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／少し笑う】","text":"分かった分かった"},
                {"id":"win-029","speaker":"narration","text":"","direction":"千鶴が戻っていく","hide":["chizuru"]},
                {"id":"win-030","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁／小さく】","text":"……なんやねん"},
                {"id":"win-031","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"何が？"},
                {"id":"win-032","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"お前には言うてへん"},
                {"id":"win-033","speaker":"narration","text":"","direction":"画面暗転","hide":"all","effect":"fadeOut"}
            ]
        },
        {
            "id": "lose",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                {"id":"lose-001","speaker":"mai","position":"left","expression":"laugh", "pose": "cheer","direction":"【左：舞依／少し笑う】","text":"また私の勝ち"},
                {"id":"lose-002","speaker":"chizuru","position":"right","expression":"pout","direction":"【右：千鶴／むっとする】","text":"……二連敗",
                "motion": "tremble",
                "mark": "…",
                "se": "shock"},
                {"id":"lose-003","speaker":"mai","position":"left","expression":"smile","direction":"【左：舞依／笑顔】","text":"もう一回する？"},
                {"id":"lose-004","speaker":"chizuru","position":"right","expression":"pout","direction":"【右：千鶴／むっとする】","text":"する。次こそ勝つ！",
                "motion": "zoom",
                "mark": "!"}
            ]
        }
    ],
    "battle": {
        "after": "battle-start",
        "player": "chizuru",
        "cpu": "mai",
        "playerSkill": "choose",
        "cpuSkill": "random",
        "cpuPersonality": "default"
    },
    "afterBattle": {
        "win": "win",
        "lose": "lose"
    },
    "clear": {
        "title": "六人でやれば",
        "next": {
            "number": 10,
            "title": "また会おう"
        }
    },
    "arc": "festival"
});
