// 台本原本: docs/story/episode5-scenario.md
// 敗北会話: docs/story/lose-lines-ep5-7.md（オーナー確認待ち、表示上の注記なし）
window.BattleStoryData.register({
    "id": "episode5",
    "number": 5,
    "arc": "festival",
    "title": "いい匂いのする方へ",
    "protagonist": "mai",
    "unlockRequires": "episode4",
    "summary": "文化祭に来た舞依と拓海。いい匂いに誘われて入った教室で、舞依は千鶴と出会う。",
    "defaultPositions": {
        "chizuru": "left",
        "kanna": "left",
        "mai": "right",
        "takumi": "left",
        "akatsuki": "left",
        "tsuyoshi": "left"
    },
    "scenes": [
        {
            "id": "scene1",
            "background": "festival-hallway",
            "bgm": "story",
            "lines": [
                { "id": "scene1-001", "speaker": "narration", "text": "", "direction": "文化祭で賑わう校内。" },
                { "id": "scene1-002", "speaker": "narration", "text": "", "direction": "模擬店の看板や装飾が並び、多くの生徒や来場者が歩いている。" },
                { "id": "scene1-003", "speaker": "mai", "position": "right", "expression": "normal", "pose": "behind", "direction": "【右：舞依／通常】", "text": "人、多いですね" },
                { "id": "scene1-004", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-005", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "文化祭だからね" },
                { "id": "scene1-006", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "知り合いのクラス、もう少し先だよ" },
                { "id": "scene1-007", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene1-008", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "はい" },
                { "id": "scene1-009", "speaker": "narration", "text": "", "direction": "少し歩く。" },
                { "id": "scene1-010", "speaker": "mai", "position": "right", "expression": "surprised", "direction": "【右：舞依／何かに気づく】", "text": "……",
                "mark": "sparkle",
                "se": "idea" },
                { "id": "scene1-011", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-012", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "どうしたの？" },
                { "id": "scene1-013", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene1-014", "speaker": "mai", "position": "right", "expression": "surprised", "direction": "【右：舞依】", "text": "拓海先輩" },
                { "id": "scene1-015", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【舞依・少し嬉しそう】", "text": "いい匂いします",
                "mark": "sparkle" },
                { "id": "scene1-016", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-017", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／困り気味】", "text": "え？" },
                { "id": "scene1-018", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene1-019", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "こっち" },
                { "id": "scene1-020", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-021", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海】", "text": "舞依、知り合いのところは？" },
                { "id": "scene1-022", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene1-023", "speaker": "mai", "position": "right", "expression": "normal", "pose": "default", "direction": "【右：舞依／通常】", "text": "あとでいいです" },
                { "id": "scene1-024", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "お腹空きました" },
                { "id": "scene1-025", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-026", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海／苦笑】", "text": "……そっか" },
                { "id": "scene1-027", "speaker": "narration", "text": "", "direction": "舞依が迷わず匂いのする方向へ歩いていく。" },
                { "id": "scene1-028", "speaker": "narration", "text": "", "direction": "拓海も後をついていく。" }
            ]
        },
        {
            "id": "scene2",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene2-001", "speaker": "narration", "text": "", "direction": "教室にはカレーやおにぎりのメニュー。" },
                { "id": "scene2-002", "speaker": "narration", "text": "", "direction": "数組の客が食事をしている。" },
                { "id": "scene2-003", "speaker": "narration", "text": "", "direction": "舞依と拓海が席につく。" },
                { "id": "scene2-004", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依／メニューを見る】", "text": "カレー" },
                { "id": "scene2-005", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-006", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海】", "text": "入って一秒くらいで決めたね" },
                { "id": "scene2-007", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-008", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "匂いで決めてました" },
                { "id": "scene2-009", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-010", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "じゃあ僕はキーマカレーにしようかな" },
                { "id": "scene2-011", "speaker": "narration", "text": "", "direction": "少し間。", "wait": 800 },
                { "id": "scene2-012", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "注文って、ここで待ってたらいいのかな？" },
                { "id": "scene2-013", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-014", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "多分" },
                { "id": "scene2-015", "speaker": "narration", "text": "", "direction": "少しして千鶴がやってくる。" },
                { "id": "scene2-016", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "text": "いらっしゃい！",
                "motion": "slideIn",
                "se": "swish" },
                { "id": "scene2-017", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴】", "text": "注文決まった？" },
                { "id": "scene2-018", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene2-019", "speaker": "mai", "position": "right", "expression": "gentle", "pose": "behind", "direction": "【右：舞依／少し柔らかい表情】", "text": "カレーお願いします" },
                { "id": "scene2-020", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-021", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "カレー一つ" },
                { "id": "scene2-022", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴】", "text": "そっちは？" },
                { "id": "scene2-023", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene2-024", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "キーマカレーをお願いします" },
                { "id": "scene2-025", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-026", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "text": "了解。ちょっと待っててね！",
                "mark": "!" },
                { "id": "scene2-027", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene2-028", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "待って" },
                { "id": "scene2-029", "speaker": "narration", "text": "", "direction": "千鶴が振り返る。" },
                { "id": "scene2-030", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "ん？" },
                { "id": "scene2-031", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene2-032", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "名前、千鶴ちゃん？" },
                { "id": "scene2-033", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-034", "speaker": "chizuru", "position": "left", "expression": "surprised", "direction": "【左：千鶴／少し驚く】", "text": "そうだよ" },
                { "id": "scene2-035", "speaker": "chizuru", "position": "left", "expression": "surprised", "direction": "【左：千鶴】", "text": "なんで分かったの？",
                "mark": "?" },
                { "id": "scene2-036", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene2-037", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "名札" },
                { "id": "scene2-038", "speaker": "mai", "position": "right", "expression": "laugh", "direction": "【舞依・少し笑う】", "text": "かわいい名前",
                "mark": "note" },
                { "id": "scene2-039", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-040", "speaker": "chizuru", "position": "left", "expression": "embarrassed", "direction": "【左：千鶴／照れ】", "pose": "behind", "text": "えっ",
                "mark": "sweat" },
                { "id": "scene2-041", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【左：千鶴／少し嬉しそう】", "text": "ありがとう！",
                "mark": "sparkle" },
                { "id": "scene2-042", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene2-043", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依】", "text": "私は舞依" },
                { "id": "scene2-044", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【舞依】", "text": "こっちは拓海先輩" },
                { "id": "scene2-045", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-046", "speaker": "takumi", "position": "left", "expression": "gentle", "direction": "【左：拓海／柔らかい笑顔】", "text": "よろしく" },
                { "id": "scene2-047", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-048", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【左：千鶴】", "text": "舞依ちゃんと拓海ね" },
                { "id": "scene2-049", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴・笑顔】", "text": "よろしく！",
                "mark": "!" },
                { "id": "scene2-050", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依／少し嬉しそう】", "text": "……" },
                { "id": "scene2-051", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-052", "speaker": "takumi", "position": "left", "expression": "gentle", "direction": "【左：拓海】", "text": "舞依？" },
                { "id": "scene2-053", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-054", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "千鶴ちゃん、かわいいですね",
                "mark": "sparkle" },
                { "id": "scene2-055", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-056-pause", "speaker": "narration", "text": "", "wait": 800, "direction": "【左：拓海／少し間】" },
                { "id": "scene2-056", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／少し間】", "text": "……そうだね" },
                { "id": "scene2-057", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-058", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "話しやすいし" },
                { "id": "scene2-059", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【舞依】", "text": "好きかも" },
                { "id": "scene2-060", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-061", "speaker": "takumi", "position": "left", "expression": "frozen", "direction": "【左：拓海／少し固まる】", "text": "……早くない？",
                "motion": "tremble",
                "mark": "…",
                "se": "shock" },
                { "id": "scene2-062", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene2-063", "speaker": "mai", "position": "right", "expression": "normal", "pose": "default", "direction": "【右：舞依／通常】", "text": "そうですか？" },
                { "id": "scene2-064", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "かわいい女の子を好きになるのに時間いります？" },
                { "id": "scene2-065", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-066", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "……いや" },
                { "id": "scene2-067", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／小声】", "text": "そういう意味じゃないんだけどな……" }
            ]
        },
        {
            "id": "scene3",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene3-001", "speaker": "narration", "text": "", "direction": "少しして千鶴が戻ってくる。" },
                { "id": "scene3-002", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "もうちょっとでできるって" },
                { "id": "scene3-003", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴】", "pose": "behind", "text": "ごめん、少しだけ待ってて" },
                { "id": "scene3-004", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene3-005", "speaker": "mai", "position": "right", "expression": "normal", "pose": "behind", "direction": "【右：舞依】", "text": "全然大丈夫" },
                { "id": "scene3-006", "speaker": "narration", "text": "", "direction": "舞依が机の端に置いてあるカードに気づく。" },
                { "id": "scene3-007", "speaker": "mai", "position": "right", "expression": "thinking", "pose": "default", "direction": "【右：舞依／興味】", "text": "これ……" },
                { "id": "scene3-008", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【舞依】", "text": "Battle à la carte？" },
                { "id": "scene3-009", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene3-010", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【左：千鶴／嬉しそう】", "text": "知ってるの？" },
                { "id": "scene3-011", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene3-012", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依】", "text": "やってます" },
                { "id": "scene3-013", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene3-014", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【左：千鶴】", "text": "ほんと？" },
                { "id": "scene3-015", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "pose": "cheer", "text": "じゃあやろ！",
                "mark": "!" },
                { "id": "scene3-016", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene3-017", "speaker": "mai", "position": "right", "expression": "surprised", "direction": "【右：舞依／少し驚く】", "text": "今？",
                "motion": "hop",
                "mark": "!",
                "se": "pop" },
                { "id": "scene3-018", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene3-019", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "今！",
                "mark": "!" },
                { "id": "scene3-020", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "text": "料理できるまでちょっと時間あるから" },
                { "id": "scene3-021", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene3-022", "speaker": "mai", "position": "right", "expression": "smile", "pose": "cheer", "direction": "【右：舞依／笑顔】", "text": "やります" },
                { "id": "scene3-023", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene3-024", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海】", "text": "舞依も即答なんだ……" },
                { "id": "scene3-025", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene3-026", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依】", "text": "だって千鶴ちゃんと遊べるので" },
                { "id": "scene3-027", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene3-028", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／微妙な表情】", "text": "……そっか" },
                { "id": "scene3-029", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依】", "text": "拓海先輩" },
                { "id": "scene3-030", "speaker": "mai", "position": "right", "expression": "cold", "pose": "default", "direction": "【舞依・少し冷たい】", "text": "なんですか、その顔" },
                { "id": "scene3-031", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene3-032", "speaker": "takumi", "position": "left", "expression": "flustered", "direction": "【左：拓海／焦り】", "text": "え？",
                "motion": "tremble",
                "mark": "sweat" },
                { "id": "scene3-033", "speaker": "takumi", "position": "left", "expression": "flustered", "direction": "【左：拓海】", "text": "いや、何でもないよ" },
                { "id": "scene3-034", "speaker": "mai", "position": "right", "expression": "cold", "direction": "【右：舞依】", "text": "ならいいです" },
                { "id": "battle-start", "speaker": "narration", "text": "", "battle": true, "direction": "BATTLE START" }
            ]
        },
        {
            "id": "win",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "win-001", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【右：舞依／少し嬉しそう】", "text": "勝ちました" },
                { "id": "win-002", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "win-003", "speaker": "chizuru", "position": "left", "expression": "sad", "direction": "【左：千鶴／悔しそう】", "pose": "behind", "text": "負けた……" },
                { "id": "win-004", "speaker": "chizuru", "position": "left", "expression": "sad", "direction": "【左：千鶴】", "text": "舞依ちゃん強いね" },
                { "id": "win-005", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "win-006", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "千鶴ちゃんも強かったよ" },
                { "id": "win-007", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依／笑顔】", "text": "またやろ" },
                { "id": "win-008", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "win-009", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "pose": "default", "text": "うん！",
                "motion": "hop",
                "mark": "sparkle",
                "se": "sparkle" },
                { "id": "win-010", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "次は勝つ！",
                "motion": "zoom",
                "mark": "!" },
                { "id": "win-011", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "win-012", "speaker": "mai", "position": "right", "expression": "smile", "pose": "default", "direction": "【右：舞依】", "text": "じゃあ次も私が勝つ" },
                { "id": "win-013", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "win-014", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【左：千鶴／楽しそう】", "text": "いいよ！",
                "mark": "!" },
                { "id": "win-015", "speaker": "narration", "text": "", "direction": "二人が笑う。" },
                { "id": "win-016", "speaker": "narration", "text": "", "direction": "少し離れたところ。" },
                { "id": "win-017", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海／通常】", "text": "……" },
                { "id": "win-018", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海／小声】", "text": "もう仲良くなってる……" },
                { "id": "win-019", "speaker": "narration", "text": "", "direction": "そのタイミングで料理が運ばれてくる。" },
                { "id": "win-020", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／料理を持って登場】", "text": "お待たせ",
                "motion": "slideIn",
                "se": "swish" },
                { "id": "win-021", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "カレーとキーマカレー" },
                { "id": "win-022", "speaker": "narration", "text": "", "hide": [ "kanna" ], "direction": "【栞那・消える】" },
                { "id": "win-023", "speaker": "mai", "position": "right", "expression": "happy", "pose": "behind", "direction": "【右：舞依／嬉しそう】", "text": "ありがとうございます" },
                { "id": "win-024", "speaker": "narration", "text": "", "direction": "舞依が千鶴を見る。" },
                { "id": "win-025", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "千鶴ちゃん" },
                { "id": "win-026", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【舞依／笑顔】", "text": "またあとで" },
                { "id": "win-027", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "win-028", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "text": "うん。ゆっくり食べてね" },
                { "id": "win-029", "speaker": "narration", "text": "", "direction": "千鶴が厨房へ戻っていく。", "hide": [ "chizuru" ] },
                { "id": "win-030", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依／千鶴を目で追う】", "text": "……かわいい" },
                { "id": "win-031", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "win-032", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／少し困る】", "text": "舞依" },
                { "id": "win-033", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【拓海】", "text": "カレー冷めるよ" },
                { "id": "win-034", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依】", "text": "食べます" },
                { "id": "win-035", "speaker": "narration", "text": "", "direction": "暗転。", "hide": "all", "effect": "fadeOut" }
            ]
        },
        {
            "id": "lose",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "lose-001", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "pose": "cheer", "text": "勝った！" },
                { "id": "lose-002", "speaker": "mai", "position": "right", "expression": "surprised", "direction": "【右：舞依／少し驚く】", "text": "……強い" },
                { "id": "lose-003", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "text": "料理できるまで、もう一回やる？" },
                { "id": "lose-004", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依／笑顔】", "text": "やる。次は勝つ" }
            ]
        }
    ],
    "battle": {
        "after": "battle-start",
        "player": "mai",
        "cpu": "chizuru",
        "playerSkill": "choose",
        "cpuSkill": "random",
        "cpuPersonality": "default"
    },
    "afterBattle": {
        "win": "win",
        "lose": "lose"
    },
    "clear": {
        "title": "いい匂いのする方へ",
        "next": {
            "number": 6,
            "title": "もう少し、ここにいたい"
        }
    }
});
