// 台本原本: docs/story/episode7-scenario.md
// 敗北会話: docs/story/lose-lines-ep5-7.md（オーナー確認待ち、表示上の注記なし）
window.BattleStoryData.register({
    "id": "episode7",
    "number": 7,
    "title": "うるさい二人が来た",
    "protagonist": "chizuru",
    "unlockRequires": "episode6",
    "summary": "廊下から聞こえてくる、うるさい二人の声。注文を聞きに行った千鶴は、さっそくいじられて……。",
    "defaultPositions": {
        "chizuru": "right",
        "kanna": "left",
        "mai": "left",
        "takumi": "left",
        "akatsuki": "left",
        "tsuyoshi": "left"
    },
    "scenes": [
        {
            "id": "scene1",
            "background": "festival-kitchen",
            "bgm": "story",
            "lines": [
                { "id": "scene1-001", "speaker": "narration", "text": "", "direction": "舞依と拓海も加わり、四人で料理の準備を進めている。" },
                { "id": "scene1-002", "speaker": "narration", "text": "", "direction": "教室の外から、大きな声が近づいてくる。" },
                { "id": "scene1-003", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "", "text": "せやから俺は悪ないって！", "offscreen": true },
                { "id": "scene1-004", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "", "text": "いや、お前が全部悪い。", "offscreen": true },
                { "id": "scene1-005", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "", "text": "全部は言い過ぎやろ！", "offscreen": true },
                { "id": "scene1-006", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "", "text": "ほな九割五分。", "offscreen": true },
                { "id": "scene1-007", "speaker": "mai", "position": "right", "expression": "angry", "direction": "【右：舞依／真顔】", "text": "……来ましたね。" },
                { "id": "scene1-008", "speaker": "kanna", "position": "left", "expression": "angry", "direction": "【左：栞那／少し嫌そう】", "text": "うるさいのが。" },
                { "id": "scene1-009", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／苦笑】", "text": "廊下にいる時点で声聞こえてたもんね。" },
                { "id": "scene1-010", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "入ってこないでほしいです。" },
                { "id": "scene1-011", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴／入口を見る】", "text": "お客さんなら入ってくるでしょ。" },
                { "id": "scene1-012", "speaker": "narration", "text": "", "direction": "二人の男子生徒が教室へ入ってくる。" },
                { "id": "scene1-013", "speaker": "tsuyoshi", "position": "left", "expression": "smile", "direction": "【左：剛／元気】", "text": "おお、ここやここ！" },
                { "id": "scene1-014", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁／通常】", "text": "声でかいねん。見たら分かる。" },
                { "id": "scene1-015", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "いやでも俺、店入る時は元気よくって教わったから。" },
                { "id": "scene1-016", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "誰にやねん。" },
                { "id": "scene1-017", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "おかん。" },
                { "id": "scene1-018", "speaker": "akatsuki", "position": "left", "expression": "troubled", "direction": "【暁／少し呆れる】", "text": "お前ん家の教育どうなってんねん。" },
                { "id": "scene1-019", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／小声】", "text": "……やっぱりうるさい。" },
                { "id": "scene1-020", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依／小声】", "text": "ですね。" },
                { "id": "scene1-021", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "まあまあ。" },
                { "id": "scene1-022", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴／普通】", "text": "私、注文聞いてくる。" },
                { "id": "scene1-023", "speaker": "kanna", "position": "left", "expression": "surprised", "direction": "【左：栞那／少し驚く】", "text": "千鶴が行くの？" },
                { "id": "scene1-024", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "うん。" },
                { "id": "scene1-025", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "お客さんだし。" },
                { "id": "scene1-026", "speaker": "narration", "text": "", "direction": "千鶴が暁と剛のテーブルへ向かう。" },
                { "id": "scene1-027", "speaker": "narration", "text": "", "direction": "少し離れたところ。" },
                { "id": "scene1-028", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／千鶴を見る】", "text": "私、千鶴のああいうところ真似できない。" },
                { "id": "scene1-029", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／少し笑う】", "text": "尊敬する。" },
                { "id": "scene1-030", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "それな。" },
                { "id": "scene1-031", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "二人とも聞こえたら怒られるよ。" },
                { "id": "scene1-032", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "千鶴は怒らないよ。" }
            ]
        },
        {
            "id": "scene2",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene2-001", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／笑顔】", "text": "いらっしゃい。" },
                { "id": "scene2-002", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "注文決まった？" },
                { "id": "scene2-003", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【左：剛／メニューを見る】", "text": "俺、全部。" },
                { "id": "scene2-004", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁／即座に】", "text": "アホか。" },
                { "id": "scene2-005", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "なんでやねん。腹減ってんねん。" },
                { "id": "scene2-006", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "財布の中見てから言え。" },
                { "id": "scene2-007", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛／ポケット確認】", "text": "……。" },
                { "id": "scene2-008", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "なんぼあんねん。" },
                { "id": "scene2-009", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "七百円。" },
                { "id": "scene2-010", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／少し笑う】", "text": "全部どころか二つも怪しいやんけ。" },
                { "id": "scene2-011", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／笑う】", "text": "ふふっ。" },
                { "id": "scene2-012", "speaker": "narration", "text": "", "direction": "暁が千鶴を見る。" },
                { "id": "scene2-013", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁】", "text": "……笑うとこあった？" },
                { "id": "scene2-014", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "あったよ。" },
                { "id": "scene2-015", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "二人、面白いね。" },
                { "id": "scene2-016", "speaker": "tsuyoshi", "position": "left", "expression": "smile", "direction": "【左：剛／嬉しそう】", "text": "ほら見ろ！" },
                { "id": "scene2-017", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "俺らおもろいねん！" },
                { "id": "scene2-018", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁】", "text": "一人で俺らにすんな。" },
                { "id": "scene2-019", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "じゃあ俺がおもろい！" },
                { "id": "scene2-020", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "それはもっと違う。" },
                { "id": "scene2-021", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／笑顔】", "text": "で、何にする？" },
                { "id": "scene2-022", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "俺カレー。" },
                { "id": "scene2-023", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "俺キーマ。" },
                { "id": "scene2-024", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "カレーとキーマね。" },
                { "id": "scene2-025", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴／少し考える】", "text": "カレー、おいしいよ。" },
                { "id": "scene2-026", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "店員が自分で言うんや。" },
                { "id": "scene2-027", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "ほんとにおいしいから。" },
                { "id": "scene2-028", "speaker": "akatsuki", "position": "left", "expression": "smug", "direction": "【暁／少し意地悪そう】", "text": "自分で結構食ったんちゃう？" },
                { "id": "scene2-029", "speaker": "chizuru", "position": "right", "expression": "surprised", "direction": "【右：千鶴／一瞬止まる】", "text": "……なんで分かったの？" },
                { "id": "scene2-030", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／笑う】", "text": "当たったんかい。" },
                { "id": "scene2-031", "speaker": "tsuyoshi", "position": "left", "expression": "smile", "direction": "【剛／笑う】", "text": "顔に書いてあるんちゃう？" },
                { "id": "scene2-032", "speaker": "chizuru", "position": "right", "expression": "angry", "direction": "【千鶴／不満】", "text": "書いてない。" },
                { "id": "scene2-033", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "いや、だいぶ書いてる。" },
                { "id": "scene2-034", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "書いてないって。" },
                { "id": "scene2-035", "speaker": "narration", "text": "", "direction": "少し離れたところ。" },
                { "id": "scene2-036", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑いをこらえる】", "text": "もういじられてる。" },
                { "id": "scene2-037", "speaker": "mai", "position": "right", "expression": "angry", "direction": "【右：舞依／少し不満】", "text": "千鶴ちゃんに絡むの早くないですか。" },
                { "id": "scene2-038", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "でも千鶴、楽しそうだよ。" },
                { "id": "scene2-039", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "……それはそうですけど。" }
            ]
        },
        {
            "id": "scene3",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene3-001", "speaker": "narration", "text": "", "direction": "料理を待つ暁と剛。" },
                { "id": "scene3-002", "speaker": "narration", "text": "", "direction": "剛が机に置かれていたBattle à la carteのカードを見る。" },
                { "id": "scene3-003", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【左：剛】", "text": "なんやこれ？" },
                { "id": "scene3-004", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "Battle à la carte。" },
                { "id": "scene3-005", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "カードゲーム？" },
                { "id": "scene3-006", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "うん。" },
                { "id": "scene3-007", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【千鶴／少し嬉しそう】", "text": "料理を作って勝負するゲーム。" },
                { "id": "scene3-008", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁】", "text": "料理の店で料理のカードゲームやるんや。" },
                { "id": "scene3-009", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "いいでしょ。" },
                { "id": "scene3-010", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "別に悪いとは言うてへん。" },
                { "id": "scene3-011", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛／カードを手に取る】", "text": "これ勝負できるん？" },
                { "id": "scene3-012", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "できるよ。" },
                { "id": "scene3-013", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "ほなやろうや！" },
                { "id": "scene3-014", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "お前ルール知らんやろ。" },
                { "id": "scene3-015", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "今から覚えたらええ。" },
                { "id": "scene3-016", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "注文した飯冷めるわ。" },
                { "id": "scene3-017", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "じゃあ暁やれや。" },
                { "id": "scene3-018", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "なんで俺やねん。" },
                { "id": "scene3-019", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "なんとなく。" },
                { "id": "scene3-020", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "理由弱すぎるやろ。" },
                { "id": "scene3-021", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴／暁を見る】", "text": "やらない？" },
                { "id": "scene3-022", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "俺？" },
                { "id": "scene3-023", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "うん。" },
                { "id": "scene3-024", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "暇でしょ？" },
                { "id": "scene3-025", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／少し笑う】", "text": "客に向かって暇でしょって言う店員初めて見たわ。" },
                { "id": "scene3-026", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "違うの？" },
                { "id": "scene3-027", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "……まあ暇やけど。" },
                { "id": "scene3-028", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "決まりやな！" },
                { "id": "scene3-029", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "お前が決めんな。" }
            ]
        },
        {
            "id": "scene4",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene4-001", "speaker": "narration", "text": "", "effect": "battleTease", "direction": "対戦前演出" },
                { "id": "scene4-002", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "じゃあやろ。" },
                { "id": "scene4-003", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "そういえば、名前聞いてなかった。" },
                { "id": "scene4-004", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【左：剛】", "text": "俺、剛。" },
                { "id": "scene4-005", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁】", "text": "暁。" },
                { "id": "scene4-006", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "剛と暁ね。" },
                { "id": "scene4-007", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁】", "text": "覚える気あるんや。" },
                { "id": "scene4-008", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "あるよ。お客さんだし。" },
                { "id": "scene4-009", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【左：暁／少し笑う】", "text": "真面目なんか適当なんか分からんな。" },
                { "id": "scene4-010", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "失礼。" },
                { "id": "scene4-011", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【左：暁】", "text": "ええけど。" },
                { "id": "scene4-012", "speaker": "akatsuki", "position": "left", "expression": "smug", "direction": "【暁／少し挑発的】", "text": "負けても泣くなよ。" },
                { "id": "scene4-013", "speaker": "chizuru", "position": "right", "expression": "angry", "direction": "【右：千鶴／むっとする】", "text": "泣かないし。" },
                { "id": "scene4-014", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "ほんま？" },
                { "id": "scene4-015", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "ほんと。" },
                { "id": "scene4-016", "speaker": "akatsuki", "position": "left", "expression": "smug", "direction": "【暁／薄く笑う】", "text": "その顔、もうちょいで泣きそうやけど。" },
                { "id": "scene4-017", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "まだ始まってもない！" },
                { "id": "scene4-018", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／離れたところから】", "text": "千鶴、もう遊ばれてるじゃん。" },
                { "id": "scene4-019", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴／栞那を見る】", "text": "栞那まで言わないで。" },
                { "id": "scene4-020", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁／栞那を見る】", "text": "普段からこんな感じなん？" },
                { "id": "scene4-021", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／笑顔】", "text": "うん。" },
                { "id": "scene4-022", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "反応いいでしょ。" },
                { "id": "scene4-023", "speaker": "chizuru", "position": "right", "expression": "angry", "direction": "【千鶴／不満】", "text": "二人で意気投合しないで。" },
                { "id": "scene4-024", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／少し笑う】", "text": "なるほどな。" },
                { "id": "scene4-025", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "何が？" },
                { "id": "scene4-026", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "いや、なんでもない。" },
                { "id": "battle-start", "speaker": "narration", "text": "", "battle": true, "direction": "BATTLE START" }
            ],
            "battleIntro": true
        },
        {
            "id": "win",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "win-001", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／嬉しそう】", "text": "勝った！" },
                { "id": "win-002", "speaker": "akatsuki", "position": "left", "expression": "troubled", "direction": "【左：暁／少し悔しそう】", "text": "……マジか。" },
                { "id": "win-003", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／得意げ】", "text": "泣かなかったでしょ。" },
                { "id": "win-004", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "勝ったんやから当たり前やろ。" },
                { "id": "win-005", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "暁こそ泣かないでね。" },
                { "id": "win-006", "speaker": "akatsuki", "position": "left", "expression": "surprised", "direction": "【暁／一瞬止まる】", "text": "……言うようになったな。" },
                { "id": "win-007", "speaker": "tsuyoshi", "position": "left", "expression": "smile", "direction": "【剛／大笑い】", "text": "負けとるやん！" },
                { "id": "win-008", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "うるさい。" },
                { "id": "win-009", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "俺がやったほうが強かったんちゃう？" },
                { "id": "win-010", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "ルール知らんやつが何言うてんねん。" }
            ],
            "next": "scene5"
        },
        {
            "id": "scene5",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene5-001", "speaker": "narration", "text": "", "direction": "料理が運ばれてくる。" },
                { "id": "scene5-002", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那】", "text": "はい、カレーとキーマ。" },
                { "id": "scene5-003", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "来た！" },
                { "id": "scene5-004", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "お前今日一番でかい声それやん。" },
                { "id": "scene5-005", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "飯は大事や。" },
                { "id": "scene5-006", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【右：千鶴】", "text": "冷める前に食べてね。" },
                { "id": "scene5-007", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "いただきます！" },
                { "id": "scene5-008", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "いただきます。" },
                { "id": "scene5-009", "speaker": "narration", "text": "", "direction": "少し時間経過。" },
                { "id": "scene5-010", "speaker": "tsuyoshi", "position": "left", "expression": "smile", "direction": "【剛／嬉しそう】", "text": "うま！" },
                { "id": "scene5-011", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "普通にうまいな。" },
                { "id": "scene5-012", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【千鶴／嬉しそう】", "text": "でしょ？" },
                { "id": "scene5-013", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "なんでお前がそんな誇らしげやねん。" },
                { "id": "scene5-014", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "作ったから。" },
                { "id": "scene5-015", "speaker": "akatsuki", "position": "left", "expression": "surprised", "direction": "【暁／少し驚く】", "text": "これ作ったん？" },
                { "id": "scene5-016", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "栞那と一緒に。" },
                { "id": "scene5-017", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "千鶴、料理はちゃんとできるよ。" },
                { "id": "scene5-018", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／少し意地悪】", "text": "つまみ食いも多いけど。" },
                { "id": "scene5-019", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "またそれ言う。" },
                { "id": "scene5-020", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／笑う】", "text": "やっぱ食ってるやん。" },
                { "id": "scene5-021", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "味見！" },
                { "id": "scene5-022", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "はいはい、味見な。" },
                { "id": "scene5-023", "speaker": "chizuru", "position": "right", "expression": "angry", "direction": "【千鶴／不満】", "text": "絶対信じてない。" },
                { "id": "scene5-024", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "よう分かったな。" },
                { "id": "scene5-025", "speaker": "narration", "text": "", "direction": "少し離れたところ。" },
                { "id": "scene5-026", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依／千鶴を見る】", "text": "……。" },
                { "id": "scene5-027", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "どうしたの？" },
                { "id": "scene5-028", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "あの人、千鶴ちゃんいじりすぎじゃないですか。" },
                { "id": "scene5-029", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【拓海／少し笑う】", "text": "千鶴もちゃんと返してるし、大丈夫じゃない？" },
                { "id": "scene5-030", "speaker": "mai", "position": "right", "expression": "angry", "direction": "【舞依／少し不満】", "text": "……。" },
                { "id": "scene5-031", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【拓海】", "text": "舞依？" },
                { "id": "scene5-032", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "別に。" }
            ],
            "next": "scene6"
        },
        {
            "id": "scene6",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene6-001", "speaker": "narration", "text": "", "direction": "食事を終えた暁と剛。" },
                { "id": "scene6-002", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "ここ当たりやったな。" },
                { "id": "scene6-003", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "珍しくお前にしてはええ判断やった。" },
                { "id": "scene6-004", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "俺が見つけたみたいに言うな。" },
                { "id": "scene6-005", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "お前が言うたんやろが。" },
                { "id": "scene6-006", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／笑顔】", "text": "また来てね。" },
                { "id": "scene6-007", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "気が向いたらな。" },
                { "id": "scene6-008", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "来ないやつだ。" },
                { "id": "scene6-009", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／笑う】", "text": "なんで決めつけんねん。" },
                { "id": "scene6-010", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "俺は来るで！" },
                { "id": "scene6-011", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "お前金ないやろ。" },
                { "id": "scene6-012", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "……明日ならある。" },
                { "id": "scene6-013", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "文化祭今日だけや。" },
                { "id": "scene6-014", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／少し笑う】", "text": "ほんとうるさい二人。" },
                { "id": "scene6-015", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "同感です。" },
                { "id": "scene6-016", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "でも、悪い人ではなさそうだけどね。" },
                { "id": "scene6-017", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "まだ分かりません。" },
                { "id": "scene6-018", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【右：千鶴／楽しそう】", "text": "面白かったよ。" },
                { "id": "scene6-019", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁／千鶴を見る】", "text": "お前は誰とでも楽しそうやな。" },
                { "id": "scene6-020", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "楽しいから。" },
                { "id": "scene6-021", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "……そらええことやな。" },
                { "id": "scene6-022", "speaker": "narration", "text": "", "direction": "少し間。", "wait": 800 },
                { "id": "scene6-023", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "なんか今日、一気に知らんやつ増えたな。" },
                { "id": "scene6-024", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "お前が勝手に喋ってるからやろ。" },
                { "id": "scene6-025", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "でも、楽しいですよ。" },
                { "id": "scene6-026", "speaker": "chizuru", "position": "right", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "うん。" },
                { "id": "scene6-027", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "千鶴は何でも楽しそうだけどね。" },
                { "id": "scene6-028", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "楽しいよ？" },
                { "id": "scene6-029", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／笑う】", "text": "知ってる。" },
                { "id": "scene6-030", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【暁／小さく笑う】", "text": "ほんま分かりやすいな。" },
                { "id": "scene6-031", "speaker": "chizuru", "position": "right", "expression": "normal", "direction": "【千鶴】", "text": "なにが？" },
                { "id": "scene6-032", "speaker": "akatsuki", "position": "left", "expression": "normal", "direction": "【暁】", "text": "なんでもない。" },
                { "id": "scene6-033", "speaker": "narration", "text": "", "direction": "画面暗転。", "hide": "all", "effect": "fadeOut" }
            ]
        },
        {
            "id": "lose",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "lose-001", "speaker": "akatsuki", "position": "left", "expression": "smug", "direction": "【左：暁／薄く笑う】", "text": "俺の勝ちやな。" },
                { "id": "lose-002", "speaker": "chizuru", "position": "right", "expression": "angry", "direction": "【右：千鶴／不満】", "text": "……まだ泣いてないし。" },
                { "id": "lose-003", "speaker": "akatsuki", "position": "left", "expression": "smile", "direction": "【左：暁／笑う】", "text": "誰も泣いてるとは言うてへん。" },
                { "id": "lose-004", "speaker": "chizuru", "position": "right", "expression": "angry", "direction": "【右：千鶴／むっとする】", "text": "もう一回。次は勝つ。" }
            ]
        }
    ],
    "battle": {
        "after": "battle-start",
        "player": "chizuru",
        "cpu": "akatsuki",
        "playerSkill": "choose",
        "cpuSkill": "random",
        "cpuPersonality": "default"
    },
    "afterBattle": {
        "win": "win",
        "lose": "lose"
    },
    "clear": {
        "title": "うるさい二人が来た",
        "next": {
            "number": 8,
            "title": "もう少しだけ"
        }
    }
});
