// 台本: docs/story/episode4-scenario.md。direction は日本語の原文を保持する。
window.BattleStoryData.register({
    id: 'episode4', number: 4, title: '文化祭、はじまるよ', protagonist: 'chizuru', unlockRequires: null,
    summary: '文化祭の開場前、千鶴と栞那が準備の合間にひと勝負。',
    defaultPositions: { chizuru: 'right', kanna: 'left' },
    scenes: [
        { id: 'scene1', background: 'festival-classroom', bgm: 'story', lines: [
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴／通常】', text: 'カレーよし。おにぎりもよし。' },
            { speaker: 'chizuru', position: 'right', expression: 'troubled', direction: '【右：千鶴／少し悩む】', text: '……でも、ちゃんとおいしいか確認したほうがいいよね。' },
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '【右：千鶴／笑顔】', text: '一個くらいなら。' },
            { speaker: 'narration', text: '', hide: ['chizuru'], direction: '千鶴を消す。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那／通常】', text: '千鶴。' },
            { speaker: 'narration', text: '', hide: ['kanna'], direction: '栞那を消す。' },
            { speaker: 'chizuru', position: 'right', expression: 'surprised', direction: '【右：千鶴／びくっとする】', text: '……なに？' },
            { speaker: 'narration', text: '', hide: ['chizuru'], direction: '千鶴を消す。' },
            { speaker: 'kanna', position: 'left', expression: 'smug', direction: '【左：栞那／薄い笑顔】', text: '今、何しようとしてたの？' },
            { speaker: 'narration', text: '', hide: ['kanna'], direction: '栞那を消す。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴／通常】', text: '味見。' },
            { speaker: 'narration', text: '', hide: ['chizuru'], direction: '千鶴を消す。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: 'さっきもしてたよね？' },
            { speaker: 'narration', text: '', hide: ['kanna'], direction: '栞那を消す。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: 'あれはカレー。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '続けて、', text: '今度はおにぎり。', continue: true },
            { speaker: 'narration', text: '', hide: ['chizuru'], direction: '千鶴を消す。' },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／笑顔】', text: 'なるほど。' },
            { speaker: 'kanna', position: 'left', expression: 'smug', direction: '【左：栞那／少し意地悪そう】', text: 'じゃあ千鶴の分のお昼ごはん、おにぎり一個減らしておくね。' },
            { speaker: 'narration', text: '', hide: ['kanna'], direction: '栞那を消す。' },
            { speaker: 'chizuru', position: 'right', expression: 'surprised', direction: '【右：千鶴／焦り】', text: 'なんで！？' },
            { speaker: 'narration', text: '', hide: ['chizuru'], direction: '千鶴を消す。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '今食べるんでしょ？' },
            { speaker: 'narration', text: '', hide: ['kanna'], direction: '栞那を消す。' },
            { speaker: 'chizuru', position: 'right', expression: 'troubled', direction: '【右：千鶴／困り顔】', text: '……じゃあ味見やめる。' },
            { speaker: 'narration', text: '', hide: ['chizuru'], direction: '千鶴を消す。' },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／笑顔】', text: '素直でよろしい。' }
        ] },
        { id: 'scene2', background: 'festival-classroom', lines: [
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: '栞那、そっちは終わった？' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '終わったよ。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '続けて、', text: '千鶴がつまみ食いしなければ、準備は完璧。', continue: true },
            { speaker: 'chizuru', position: 'right', expression: 'angry', direction: '【右：千鶴／不満】', text: 'まだ食べてないって。' },
            { speaker: 'kanna', position: 'left', expression: 'smug', direction: '【左：栞那／薄い笑顔】', text: '“まだ”なんだ。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: '……。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '否定しないんだ。' },
            { speaker: 'narration', text: '', wait: 800, direction: '少し間を空ける。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '開場までまだ時間あるね。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: '休憩する？' },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／笑顔】', text: 'その前に一回だけやらない？' },
            { speaker: 'narration', text: '', effect: 'battleTease', direction: 'ここでBattle à la carteを示す軽い演出。' },
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '【右：千鶴／笑顔】', text: 'やる。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '即答。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: 'だってまだ時間あるし。' },
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '続けて少し得意げに、', text: '今日も私が勝つよ。', continue: true },
            { speaker: 'kanna', position: 'left', expression: 'smug', direction: '【左：栞那／少し意地悪そう】', text: 'ずいぶん自信あるじゃん。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '続けて、', text: '負けたら今日の味見は禁止ね。', continue: true },
            { speaker: 'chizuru', position: 'right', expression: 'surprised', direction: '【右：千鶴／驚き】', text: 'えっ。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '怖くなった？' },
            { speaker: 'chizuru', position: 'right', expression: 'angry', direction: '【右：千鶴／むっとする】', text: 'やる。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '続けて、', text: '絶対勝つ。', continue: true },
            { id: 'battle-start', speaker: 'narration', text: '', battle: true, direction: 'BATTLE START' }
        ] },
        { id: 'win', background: 'festival-classroom', bgm: 'story', lines: [
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '【右：千鶴／嬉しそう】', text: '勝った！' },
            { speaker: 'kanna', position: 'left', expression: 'troubled', direction: '【左：栞那／少し悔しそう】', text: '……ほんとに勝つんだ。' },
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '【右：千鶴／得意げ】', text: 'これで味見していい？' },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／笑顔】', text: '勝ったご褒美がそれ？' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: '大事だよ。' },
            { speaker: 'kanna', position: 'left', expression: 'smug', direction: '【左：栞那／少し意地悪】', text: 'じゃあ一個だけ。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '続けて、', text: '二個食べたらお昼抜き。', continue: true },
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '【右：千鶴／笑顔】', text: 'わかった。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '続けて小声で、', text: '……大きいの選ぼ。', continue: true },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '聞こえてるよ。' },
            { speaker: 'chizuru', position: 'right', expression: 'embarrassed', direction: '【右：千鶴／焦り】', text: '普通のにする。' },
            { speaker: 'announce', name: '校内放送', text: 'まもなく文化祭を開始します。各クラス、準備をお願いします', hide: 'all', effect: 'chime', direction: 'ここで校内放送。' },
            { speaker: 'narration', text: '', effect: 'crowd', direction: '（可能なら廊下が少し賑やかになったことをSEなどで表現）' },
            { speaker: 'chizuru', position: 'right', expression: 'troubled', direction: '【右：千鶴／少し緊張】', text: 'いよいよだね。' },
            { speaker: 'kanna', position: 'left', expression: 'normal', direction: '【左：栞那】', text: '緊張してる？' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: 'ちょっとだけ。' },
            { speaker: 'chizuru', position: 'right', expression: 'smile', direction: '続けて笑顔。', text: 'でも楽しみ。', continue: true },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／柔らかい笑顔】', text: '千鶴ならそう言うと思った。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '【右：千鶴】', text: 'いっぱい来てくれるといいね。' },
            { speaker: 'chizuru', position: 'right', expression: 'normal', direction: '続けて、', text: 'せっかく作ったんだし、いっぱい食べてもらいたい。', continue: true },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／笑顔】', text: '千鶴が食べる分、残るかな。' },
            { speaker: 'chizuru', position: 'right', expression: 'angry', direction: '【右：千鶴／不満】', text: 'またそれ。' },
            { speaker: 'narration', text: '', hide: 'all', se: 'chime', effect: 'fadeOut', direction: 'チャイム。文化祭開始。画面暗転。' }
        ] },
        { id: 'lose', background: 'festival-classroom', bgm: 'story', lines: [
            { speaker: 'kanna', position: 'left', expression: 'smug', direction: '【左：栞那／少し意地悪】', text: 'はい、私の勝ち。' },
            { speaker: 'chizuru', position: 'right', expression: 'troubled', direction: '【右：千鶴／困り顔】', text: 'うう……味見禁止……。' },
            { speaker: 'kanna', position: 'left', expression: 'smile', direction: '【左：栞那／笑顔】', text: '開場まで、まだ時間あるよ。もう一回やる？' },
            { speaker: 'chizuru', position: 'right', expression: 'angry', direction: '【右：千鶴／むっとする】', text: 'やる。次は絶対勝つ。' }
        ] }
    ],
    battle: { after: 'battle-start', player: 'chizuru', cpu: 'kanna', playerSkill: 'choose', cpuSkill: 'random', cpuPersonality: 'default' },
    afterBattle: { win: 'win', lose: 'lose' },
    clear: { title: '文化祭、はじまるよ', next: { number: 5, title: 'いい匂いのする方へ' } }
});
