// 台本原本: docs/story/episode10-scenario.md（修正一覧を適用し、表示台詞の行末句点だけ除去）
// 敗北会話: docs/story/lose-lines-ep10.md（Claude案・オーナー確認待ち、内部provisionalのみ）
window.BattleStoryData.register({
    "id": "episode10",
    "number": 10,
    "arc": "festival",
    "title": "また会おう",
    "protagonist": "akatsuki",
    "unlockRequires": "episode9",
    "summary": "文化祭もいよいよおしまい。片付けの合間に、千鶴は暁にもう一度勝負を申し込む。",
    "defaultPositions": {
        "chizuru": "left",
        "kanna": "left",
        "mai": "left",
        "takumi": "left",
        "akatsuki": "right",
        "tsuyoshi": "left"
    },
    "scenes": [
        {
            "id": "scene1",
            "background": "festival-classroom-evening",
            "bgm": "story",
            "lines": [
                {"id":"scene1-001","speaker":"narration","text":"","direction":"文化祭も終わりに近づき、客足は少なくなっている"},
                {"id":"scene1-002","speaker":"narration","text":"","direction":"教室では少しずつ片付けが始まっている"},
                {"id":"scene1-003","speaker":"tsuyoshi","position":"left","expression":"tired","direction":"【左：剛／疲れた様子】","text":"終わったぁ……"},
                {"id":"scene1-004","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"まだ終わってへん"},
                {"id":"scene1-005","speaker":"tsuyoshi","position":"left","expression":"tired","direction":"【剛】","text":"気持ちはもう終わってんねん"},
                {"id":"scene1-006","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"知らんがな"},
                {"id":"scene1-007","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"俺今日めっちゃ働いたで！",
                "mark": "!"},
                {"id":"scene1-008","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"注文間違えかけたけどな"},
                {"id":"scene1-009","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"未遂や未遂！",
                "mark": "!"},
                {"id":"scene1-010","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"俺がおらんかったら成立してたわ"},
                {"id":"scene1-011","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"ほな二人のファインプレーやん！",
                "mark": "!"},
                {"id":"scene1-012","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁／呆れ】","text":"なんで共同作業みたいになってんねん"},
                {"id":"scene1-013","speaker":"narration","text":"","direction":"少し離れたところでは、千鶴と栞那が食器や備品を片付けている"},
                {"id":"scene1-014","speaker":"kanna","position":"left","expression":"normal","direction":"【左：栞那】","text":"千鶴、その箱こっち"},
                {"id":"scene1-015","speaker":"chizuru","position":"left","expression":"normal","direction":"【左：千鶴】","text":"これ？"},
                {"id":"scene1-016","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"そう"},
                {"id":"scene1-017","speaker":"chizuru","position":"left","expression":"normal","direction":"【千鶴／箱を持つ】","text":"重い",
                "motion": "shake",
                "mark": "!",
                "screen": "screenShake",
                "se": "thud"},
                {"id":"scene1-018","speaker":"kanna","position":"left","expression":"smile","direction":"【栞那／笑顔】","pose": "pocket", "text":"頑張って"},
                {"id":"scene1-019","speaker":"chizuru","position":"left","expression":"normal","direction":"【千鶴】","text":"手伝ってよ！",
                "mark": "!"},
                {"id":"scene1-020","speaker":"kanna","position":"left","expression":"smile","direction":"【栞那】","text":"千鶴ならできる"},
                {"id":"scene1-021","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴／不満】","text":"都合いい時だけ信頼しないで！",
                "motion": "shake",
                "mark": "anger",
                "se": "thud"},
                {"id":"scene1-022","speaker":"akatsuki","position":"right","expression":"thinking","direction":"【右：暁／二人を見る】","text":"……"},
                {"id":"scene1-023","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【左：剛】","text":"また見てるやん"},
                {"id":"scene1-024","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"何を"},
                {"id":"scene1-025","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"千鶴"},
                {"id":"scene1-026","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"見てへんわ"},
                {"id":"scene1-027","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"名前言うただけやで！",
                "mark": "!"},
                {"id":"scene1-028","speaker":"akatsuki","position":"right","expression":"cold","direction":"【暁／少し睨む】","text":"そのくだりさっきもやったやろ"},
                {"id":"scene1-029","speaker":"tsuyoshi","position":"left","expression":"laugh","direction":"【剛／笑う】","text":"覚えてるやん！",
                "mark": "note"},
                {"id":"scene1-030","speaker":"akatsuki","position":"right","expression":"cold","direction":"【暁】","text":"お前ほんまうるさいな"}
            ]
        },
        {
            "id": "scene2",
            "background": "festival-classroom-evening",
            "bgm": "story",
            "lines": [
                {"id":"scene2-001","speaker":"narration","text":"","direction":"舞依と拓海も手伝っている"},
                {"id":"scene2-002","speaker":"mai","position":"left","expression":"normal","direction":"【左：舞依】","text":"これ片付けたら終わり？"},
                {"id":"scene2-003","speaker":"chizuru","position":"left","expression":"normal","direction":"【左：千鶴】","text":"多分"},
                {"id":"scene2-004","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","text":"多分じゃなくて終わり"},
                {"id":"scene2-005","speaker":"chizuru","position":"left","expression":"normal","direction":"【千鶴】","text":"じゃあ終わり"},
                {"id":"scene2-006","speaker":"mai","position":"left","expression":"laugh","direction":"【舞依／少し笑う】","text":"適当"},
                {"id":"scene2-007","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"栞那が言ったから大丈夫"},
                {"id":"scene2-008","speaker":"kanna","position":"left","expression":"smug","direction":"【栞那】","pose": "pocket", "text":"そういう時だけ信用するんだ"},
                {"id":"scene2-009","speaker":"takumi","position":"left","expression":"normal","direction":"【左：拓海】","text":"なんか一日早かったね"},
                {"id":"scene2-010","speaker":"mai","position":"left","expression":"happy", "pose": "cheer","direction":"【舞依】","text":"楽しかったです"},
                {"id":"scene2-011","speaker":"takumi","position":"left","expression":"smile","direction":"【拓海／笑顔】","text":"最初は知り合いのところ行くだけの予定だったのにね"},
                {"id":"scene2-012","speaker":"mai","position":"left","expression":"happy","direction":"【舞依】","text":"予定変更して正解でした"},
                {"id":"scene2-013","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴／笑顔】","pose": "behind", "text":"来てくれてよかった",
                "mark": "sparkle"},
                {"id":"scene2-014","speaker":"mai","position":"left","expression":"happy","direction":"【舞依／嬉しそう】","text":"私も"},
                {"id":"scene2-015","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"俺らも来てよかったやろ？"},
                {"id":"scene2-016","speaker":"kanna","position":"left","expression":"exasperated","direction":"【栞那】","text":"最初はうるさいの来たと思ったけどね"},
                {"id":"scene2-017","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"最初だけ？"},
                {"id":"scene2-018","speaker":"kanna","position":"left","expression":"exasperated","direction":"【栞那】","text":"今もうるさい"},
                {"id":"scene2-019","speaker":"tsuyoshi","position":"left","expression":"surprised","direction":"【剛】","text":"変わってへんやん！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines",
                "se": "thud"},
                {"id":"scene2-020","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"そこ喜ぶとこちゃうで"}
            ]
        },
        {
            "id": "scene3",
            "background": "festival-classroom-evening",
            "bgm": "story",
            "lines": [
                {"id":"scene3-001","speaker":"narration","text":"","direction":"片付けがひと段落する"},
                {"id":"scene3-002","speaker":"narration","text":"","direction":"6人が教室に残っている"},
                {"id":"scene3-003","speaker":"mai","position":"left","expression":"smile", "pose": "behind","direction":"【左：舞依】","text":"千鶴ちゃん"},
                {"id":"scene3-004","speaker":"chizuru","position":"left","expression":"normal","direction":"【左：千鶴】","text":"ん？"},
                {"id":"scene3-005","speaker":"mai","position":"left","expression":"smile","direction":"【舞依】","text":"また会おうね"},
                {"id":"scene3-006","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴／笑顔】","text":"うん！",
                "mark": "!"},
                {"id":"scene3-007","speaker":"mai","position":"left","expression":"smile","direction":"【舞依】","text":"今度は文化祭じゃなくて普通に遊びたい"},
                {"id":"scene3-008","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"いいね！",
                "mark": "!"},
                {"id":"scene3-009","speaker":"takumi","position":"left","expression":"normal","direction":"【拓海】","text":"僕も参加していい？"},
                {"id":"scene3-010","speaker":"mai","position":"left","expression":"smile","direction":"【舞依】","text":"どうぞ"},
                {"id":"scene3-011","speaker":"takumi","position":"left","expression":"exasperated","direction":"【拓海／苦笑】","text":"許可制なんだ"},
                {"id":"scene3-012","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"ほな今度六人で集まろうや！",
                "mark": "sparkle",
                "se": "idea"},
                {"id":"scene3-013","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","pose": "pocket", "text":"いいね"},
                {"id":"scene3-014","speaker":"chizuru","position":"left","expression":"happy","direction":"【千鶴】","pose": "cheer", "text":"楽しそう！",
                "mark": "sparkle"},
                {"id":"scene3-015","speaker":"mai","position":"left","expression":"smile","direction":"【舞依】","text":"賛成"},
                {"id":"scene3-016","speaker":"takumi","position":"left","expression":"smile","direction":"【拓海】","text":"僕も"},
                {"id":"scene3-017","speaker":"narration","text":"","direction":"一瞬間が空く","wait":800},
                {"id":"scene3-018","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"……"},
                {"id":"scene3-019","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"暁は？"},
                {"id":"scene3-020","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"予定合えばな"},
                {"id":"scene3-021","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"なんやその微妙な返事"},
                {"id":"scene3-022","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"予定分からんやろ"},
                {"id":"scene3-023","speaker":"narration","text":"","direction":"千鶴が暁を見る"},
                {"id":"scene3-024","speaker":"chizuru","position":"left","expression":"happy","direction":"【左：千鶴】","text":"暁"},
                {"id":"scene3-025","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"なんや"},
                {"id":"scene3-026","speaker":"chizuru","position":"left","expression":"happy","direction":"【千鶴】","text":"その前にもう一回やろ！",
                "mark": "!"},
                {"id":"scene3-027","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"何を"},
                {"id":"scene3-028","speaker":"chizuru","position":"left","expression":"happy","direction":"【千鶴】","text":"Battle à la carte"},
                {"id":"scene3-029","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／少し笑う】","text":"まだやんの？"},
                {"id":"scene3-030","speaker":"chizuru","position":"left","expression":"happy","direction":"【千鶴】","text":"第7話で私が勝ったから"},
                {"id":"scene3-031","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"知らん知らん、話数で数えんな"},
                {"id":"scene3-032","speaker":"chizuru","position":"left","expression":"laugh","direction":"【千鶴／少し笑う】","text":"じゃあこの前勝ったから"},
                {"id":"scene3-033","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"そら覚えてるわ"},
                {"id":"scene3-034","speaker":"chizuru","position":"left","expression":"smug","direction":"【千鶴／少し挑発】","text":"負けたままでいいの？"},
                {"id":"scene3-035","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁】","text":"……"},
                {"id":"scene3-036","speaker":"tsuyoshi","position":"left","expression":"laugh","direction":"【剛／笑う】","text":"乗せられてるで",
                "mark": "note"},
                {"id":"scene3-037","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"うるさい"},
                {"id":"scene3-038","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁／千鶴を見る】","text":"ええで"},
                {"id":"scene3-039","speaker":"akatsuki","position":"right","expression":"serious","direction":"【暁】","text":"今度は負けへんからな"},
                {"id":"scene3-040","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴／笑顔】","text":"私も"},
                {
                    "id": "battle-start",
                    "speaker": "narration",
                    "text": "",
                    "direction": "FINAL BATTLE",
                    "battle": true,
                    "effect": "battleTease",
                    "finalBattle": true
                }
            ]
        },
        {
            "id": "win",
            "background": "festival-classroom-evening",
            "bgm": "story",
            "lines": [
                {"id":"win-001","speaker":"akatsuki","position":"right","expression":"smug","direction":"【右：暁／得意げ】","text":"よし"},
                {"id":"win-002","speaker":"chizuru","position":"left","expression":"frozen","direction":"【左：千鶴／固まる】","text":"……",
                "motion": "tremble",
                "mark": "…",
                "se": "shock"},
                {"id":"win-003","speaker":"akatsuki","position":"right","expression":"smug","direction":"【暁】","text":"勝ったで"},
                {"id":"win-004","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"……もう一回"},
                {"id":"win-005","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／笑う】","text":"早い早い"},
                {"id":"win-006","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"もう一回やったら勝てる！",
                "mark": "!"},
                {"id":"win-007","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"負けたやつ全員言うやつやん"},
                {"id":"win-008","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴／不満】","text":"次は勝つ！",
                "motion": "shake",
                "mark": "anger",
                "se": "thud"},
                {"id":"win-009","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"今日はもう終わりや"},
                {"id":"win-010","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"じゃあ今度"},
                {"id":"win-011","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"はいはい"},
                {"id":"win-012","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"絶対だからね！",
                "motion": "zoom",
                "mark": "!"},
                {"id":"win-013","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"何が絶対やねん"}
            ],
            "next": "scene4"
        },
        {
            "id": "scene4",
            "background": "classroom-after-festival",
            "bgm": "story",
            "lines": [
                {"id":"scene4-001","speaker":"mai","position":"left","expression":"smile", "pose": "behind","direction":"【舞依】","text":"じゃあ本当に今度みんなで集まりましょう"},
                {"id":"scene4-002","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"ええやん！",
                "mark": "!"},
                {"id":"scene4-003","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","pose": "pocket", "text":"どこ行くか考えないとね"},
                {"id":"scene4-004","speaker":"takumi","position":"left","expression":"normal","direction":"【拓海】","text":"連絡先交換しておけば決められるね"},
                {"id":"scene4-005","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"じゃあ交換しよ"},
                {"id":"scene4-006","speaker":"narration","text":"","direction":"連絡先を交換する演出","se":"notify"},
                {"id":"scene4-007","speaker":"narration","text":"","direction":"SE"},
                {"id":"scene4-008","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"俺も？",
                "mark": "?"},
                {"id":"scene4-009","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"もちろん"},
                {"id":"scene4-010","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"別にええけど"},
                {"id":"scene4-011","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"暁は絶対来るんだよ！",
                "mark": "!"},
                {"id":"scene4-012","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"なんで俺だけ念押しされてんねん"},
                {"id":"scene4-013","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"暁にまだ勝ってないから"},
                {"id":"scene4-014","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"一回勝ったやろ"},
                {"id":"scene4-015","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"今負けたから負けたまま"},
                {"id":"scene4-016","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"どういう計算やねん"},
                {"id":"scene4-017","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","pose": "behind", "text":"次会ったらまた対戦しよ"},
                {"id":"scene4-018","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／少し笑う】","text":"ええで"},
                {"id":"scene4-019","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"約束ね！",
                "mark": "!"},
                {"id":"scene4-020","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"はいはい"},
                {"id":"scene4-021","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴／不満】","text":"はいは一回"},
                {"id":"scene4-022","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／笑う】","text":"そこ気にすんの？"},
                {"id":"scene4-023","speaker":"chizuru","position":"left","expression":"pout","direction":"【千鶴】","text":"気にする"},
                {"id":"scene4-024","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁】","text":"分かった、約束"},
                {"id":"scene4-025","speaker":"chizuru","position":"left","expression":"happy","direction":"【千鶴／満足そう】","pose": "cheer", "text":"よし！",
                "mark": "sparkle"},
                {"id":"scene4-026","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛／暁を見る】","text":"お前めっちゃ来る気やん",
                "mark": "sweat"},
                {"id":"scene4-027","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"うるさいねん"},
                {"id":"scene4-028","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"約束までしてもうて"},
                {"id":"scene4-029","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"対戦するだけや"},
                {"id":"scene4-030","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【剛】","text":"はいはい"},
                {"id":"scene4-031","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"お前までそれ言うな"}
            ],
            "next": "scene5"
        },
        {
            "id": "scene5",
            "background": "school-gate-evening",
            "bgm": "story",
            "lines": [
                {"id":"scene5-001","speaker":"narration","text":"","direction":"文化祭終了"},
                {"id":"scene5-002","speaker":"narration","text":"","direction":"外は少し暗くなり始めている"},
                {"id":"scene5-003","speaker":"narration","text":"","direction":"6人が校門付近に集まる"},
                {"id":"scene5-004","speaker":"mai","position":"left","expression":"smile", "pose": "behind","direction":"【左：舞依】","text":"千鶴ちゃん、また連絡するね"},
                {"id":"scene5-005","speaker":"chizuru","position":"left","expression":"normal","direction":"【千鶴】","text":"うん"},
                {"id":"scene5-006","speaker":"mai","position":"left","expression":"happy","direction":"【舞依／少し嬉しそう】","text":"絶対する"},
                {"id":"scene5-007","speaker":"takumi","position":"left","expression":"normal","direction":"【拓海】","text":"舞依は本当にすると思うよ"},
                {"id":"scene5-008","speaker":"mai","position":"left","expression":"happy","direction":"【舞依】","text":"当たり前です"},
                {"id":"scene5-009","speaker":"kanna","position":"left","expression":"normal","direction":"【栞那】","pose": "pocket", "text":"じゃあ今日はここで解散かな"},
                {"id":"scene5-010","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"今日は楽しかったわ"},
                {"id":"scene5-011","speaker":"kanna","position":"left","expression":"smug","direction":"【栞那】","text":"今日は？"},
                {"id":"scene5-012","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"今日も！"},
                {"id":"scene5-013","speaker":"akatsuki","position":"right","expression":"exasperated","direction":"【暁】","text":"なんの修正やねん"},
                {"id":"scene5-014","speaker":"chizuru","position":"left","expression":"happy","direction":"【千鶴／みんなを見る】","pose": "cheer", "text":"今日は楽しかった",
                "mark": "sparkle"},
                {"id":"scene5-015","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴／笑顔】","text":"またみんなで遊ぼうね！",
                "mark": "!"},
                {"id":"scene5-016","speaker":"mai","position":"left","expression":"happy","direction":"【舞依】","text":"うん"},
                {"id":"scene5-017","speaker":"takumi","position":"left","expression":"normal","direction":"【拓海】","text":"またね"},
                {"id":"scene5-018","speaker":"kanna","position":"left","expression":"smile","direction":"【栞那】","text":"次も楽しみにしてる"},
                {"id":"scene5-019","speaker":"tsuyoshi","position":"left","expression":"happy","direction":"【剛】","text":"またな！"},
                {"id":"scene5-020","speaker":"narration","text":"","direction":"千鶴が暁を見る"},
                {"id":"scene5-021","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","pose": "behind", "text":"暁もね"},
                {"id":"scene5-022","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁】","text":"分かってるって"},
                {"id":"scene5-023","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"忘れないでよ"},
                {"id":"scene5-024","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"忘れへん"},
                {"id":"scene5-025","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴】","text":"次は勝つから！",
                "mark": "!"},
                {"id":"scene5-026","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【暁／少し笑う】","text":"楽しみにしとくわ"},
                {"id":"scene5-027","speaker":"chizuru","position":"left","expression":"smile","direction":"【千鶴／笑顔】","text":"うん！",
                "motion": "hop",
                "mark": "sparkle",
                "se": "sparkle"},
                {"id":"scene5-028","speaker":"narration","text":"","direction":"千鶴たちが離れていく"},
                {"id":"scene5-029","speaker":"narration","text":"","direction":"暁はその後ろ姿を見る"},
                {"id":"scene5-030","speaker":"akatsuki","position":"right","expression":"normal","direction":"【右：暁／通常】","text":"……"},
                {"id":"scene5-031","speaker":"tsuyoshi","position":"left","expression":"normal","direction":"【左：剛】","text":"行くで",
                "motion": "slideIn",
                "se": "swish"},
                {"id":"scene5-032","speaker":"akatsuki","position":"right","expression":"normal","direction":"【暁】","text":"分かってる"},
                {"id":"scene5-033","speaker":"narration","text":"","direction":"二人も歩き出す"},
                {"id":"scene5-034","speaker":"akatsuki","position":"right","expression":"thinking","direction":"","text":"最初は、ただ飯食いに入っただけやった","monologue":true},
                {"id":"scene5-035","speaker":"akatsuki","position":"right","expression":"thinking","direction":"","text":"うるさいとか、面倒くさいとか思われて","monologue":true},
                {"id":"scene5-036","speaker":"akatsuki","position":"right","expression":"thinking","direction":"","text":"まあ、いつものことや","monologue":true},
                {"id":"scene5-037","speaker":"narration","text":"","direction":"少し間","wait":800},
                {"id":"scene5-038","speaker":"akatsuki","position":"right","expression":"thinking","direction":"","text":"せやけど","monologue":true},
                {"id":"scene5-039","speaker":"akatsuki","position":"right","expression":"gentle","direction":"","text":"また会う約束までしてもうた","monologue":true},
                {"id":"scene5-040","speaker":"akatsuki","position":"right","expression":"gentle","direction":"","text":"……悪ないな","monologue":true},
                {"id":"scene5-041","speaker":"narration","text":"","direction":"画面暗転","effect":"fadeOut"}
            ]
        },
        {
            "id": "lose",
            "background": "festival-classroom-evening",
            "provisional": true,
            "lines": [
                {"id":"lose-001","speaker":"chizuru","position":"left","expression":"smile","direction":"【左：千鶴／笑顔】","pose": "cheer", "text":"勝った！ これで二勝",
                "motion": "hop",
                "mark": "sparkle",
                "se": "sparkle"},
                {"id":"lose-002","speaker":"akatsuki","position":"right","expression":"sad","direction":"【右：暁／少し悔しそう】","text":"……ほんまに強なってるやん",
                "motion": "tremble",
                "mark": "sweat"},
                {"id":"lose-003","speaker":"chizuru","position":"left","expression":"smug","direction":"【左：千鶴／少し挑発】","text":"もう一回する？"},
                {"id":"lose-004","speaker":"akatsuki","position":"right","expression":"laugh","direction":"【右：暁／少し笑う】","text":"当たり前や。今度は負けへん"}
            ]
        }
    ],
    "battle": {
        "after": "battle-start",
        "player": "akatsuki",
        "cpu": "chizuru",
        "playerSkill": "choose",
        "cpuSkill": "random",
        "cpuPersonality": "default"
    },
    "afterBattle": {
        "win": "win",
        "lose": "lose"
    },
    "clear": {
        "title": "また会おう",
        "arc": {
            "title": "出会い・文化祭編 CLEAR",
            "characters": [
                "chizuru",
                "kanna",
                "mai",
                "takumi",
                "akatsuki",
                "tsuyoshi"
            ],
            "text": "六人の物語は、ここから始まる"
        }
    }
});
