// 台本原本: docs/story/episode6-scenario.md
// 敗北会話: docs/story/lose-lines-ep5-7.md（オーナー確認待ち、表示上の注記なし）
window.BattleStoryData.register({
    "id": "episode6",
    "number": 6,
    "arc": "festival",
    "title": "もう少し、ここにいたい",
    "protagonist": "mai",
    "unlockRequires": "episode5",
    "summary": "カレーを食べながら、舞依は栞那に千鶴のことを聞いてみる。もう少しだけ、ここにいたくて――。",
    "defaultPositions": {
        "chizuru": "left",
        "kanna": "left",
        "mai": "right",
        "takumi": "left",
        "akatsuki": "left",
        "tsuyoshi": "left"
    },
    "scenes": [
        {
            "id": "scene1",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene1-001", "speaker": "narration", "text": "", "direction": "舞依と拓海の前には、出来たてのカレーとキーマカレー。" },
                { "id": "scene1-002", "speaker": "narration", "text": "", "direction": "少し離れた場所では、千鶴が別の客の対応をしている。" },
                { "id": "scene1-003", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【右：舞依／嬉しそう】", "text": "おいしい",
                "mark": "sparkle" },
                { "id": "scene1-004", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【舞依】", "text": "入って正解でした" },
                { "id": "scene1-005", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-006", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "ほんとだね。思ってたよりちゃんとしてる" },
                { "id": "scene1-007", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【拓海】", "text": "キーマも結構おいしいよ" },
                { "id": "scene1-008", "speaker": "narration", "text": "", "hide": [ "takumi" ], "direction": "【拓海・消える】" },
                { "id": "scene1-009", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "一口ください" },
                { "id": "scene1-010", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-011", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "いいよ。そっちもちょっともらっていい？" },
                { "id": "scene1-012", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "どうぞ" },
                { "id": "scene1-013", "speaker": "narration", "text": "", "direction": "少し間。", "wait": 800 },
                { "id": "scene1-014", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "……おいしい" },
                { "id": "scene1-015", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【舞依】", "text": "でも私はカレーのほうが好きです" },
                { "id": "scene1-016", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-017", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "じゃあ選んで正解だったね" },
                { "id": "scene1-018", "speaker": "narration", "text": "", "direction": "料理を運び終えた栞那が近くを通る。" },
                { "id": "scene1-019", "speaker": "mai", "position": "right", "expression": "normal", "pose": "behind", "direction": "【右：舞依】", "text": "あの" },
                { "id": "scene1-020", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-021", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／通常】", "text": "ん？" },
                { "id": "scene1-022", "speaker": "narration", "text": "", "hide": [ "kanna" ], "direction": "【栞那・消える】" },
                { "id": "scene1-023", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依】", "text": "さっきの千鶴ちゃんって、どんな子なんですか？" },
                { "id": "scene1-024", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-025", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【左：栞那／少し笑う】", "pose": "pocket", "text": "千鶴？" },
                { "id": "scene1-026", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【左：栞那】", "text": "ずいぶん気に入ったみたいだね" },
                { "id": "scene1-027", "speaker": "narration", "text": "", "hide": [ "kanna" ], "direction": "【栞那・消える】" },
                { "id": "scene1-028", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依／即答】", "text": "はい" },
                { "id": "scene1-029", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【舞依】", "text": "かわいいです" },
                { "id": "scene1-030", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene1-031", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／軽く笑う】", "text": "さっきからそればっかり言ってるよね",
                "mark": "note" },
                { "id": "scene1-032", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依】", "text": "だってかわいいので" },
                { "id": "scene1-033", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海】", "text": "はいはい" }
            ]
        },
        {
            "id": "scene2",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene2-001", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那】", "text": "千鶴は二年生" },
                { "id": "scene2-002", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那】", "text": "私の一個下で、将来はパティシエになりたいんだって" },
                { "id": "scene2-003", "speaker": "narration", "text": "", "hide": [ "kanna" ], "direction": "【栞那・消える】" },
                { "id": "scene2-004", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依／興味津々】", "text": "パティシエ" },
                { "id": "scene2-005", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-006", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那】", "text": "私も目指してるから、いつか一緒に働きたいって言ってる" },
                { "id": "scene2-007", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／少し意地悪そうな笑顔】", "pose": "pocket", "text": "まあ、本当の目的は別にある気がするけど" },
                { "id": "scene2-008", "speaker": "narration", "text": "", "hide": [ "kanna" ], "direction": "【栞那・消える】" },
                { "id": "scene2-009", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依】", "text": "別？" },
                { "id": "scene2-010", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-011", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【左：栞那】", "text": "私の料理が好きなんだよ" },
                { "id": "scene2-012", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑顔】", "text": "一緒に働けば、毎日私の料理が食べられると思ってる" },
                { "id": "scene2-013", "speaker": "narration", "text": "", "hide": [ "kanna" ], "direction": "【栞那・消える】" },
                { "id": "scene2-014", "speaker": "mai", "position": "right", "expression": "surprised", "direction": "【右：舞依／少し驚く】", "text": "……本気で？",
                "mark": "?" },
                { "id": "scene2-015", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-016", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "text": "多分、本気" },
                { "id": "scene2-017", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "text": "食べることに関しては結構真剣だから" },
                { "id": "scene2-018", "speaker": "mai", "position": "right", "expression": "laugh", "pose": "behind", "direction": "【右：舞依／少し笑う】", "text": "かわいい",
                "mark": "note" },
                { "id": "scene2-019", "speaker": "mai", "position": "right", "expression": "laugh", "direction": "【舞依】", "text": "ますます好きになりました" },
                { "id": "scene2-020", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-021", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海／少し呆れた笑顔】", "text": "どんどん好きになってるね" },
                { "id": "scene2-022", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "はい" },
                { "id": "scene2-023", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海】", "text": "……そっか" },
                { "id": "scene2-024", "speaker": "narration", "text": "", "direction": "ここだけ少し間。", "wait": 800 },
                { "id": "scene2-025", "speaker": "mai", "position": "right", "expression": "normal", "pose": "default", "direction": "【右：舞依／拓海を見る】", "text": "拓海先輩" },
                { "id": "scene2-026", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【舞依】", "text": "ちょっと不機嫌になってません？" },
                { "id": "scene2-027", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-028", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海】", "text": "少しだけ" },
                { "id": "scene2-029", "speaker": "mai", "position": "right", "expression": "cold", "direction": "【右：舞依／少し冷たい】", "text": "やめてください" },
                { "id": "scene2-030", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-031", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海／苦笑】", "text": "はいはい。分かったよ" },
                { "id": "scene2-032", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海／通常】", "text": "もう普通だから" },
                { "id": "scene2-033", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "ならいいです" },
                { "id": "scene2-034", "speaker": "narration", "text": "", "direction": "栞那が二人を見る。" },
                { "id": "scene2-035", "speaker": "kanna", "position": "left", "expression": "thinking", "direction": "【左：栞那／興味あり】", "text": "二人って付き合ってるの？" },
                { "id": "scene2-036", "speaker": "mai", "position": "right", "expression": "serious", "direction": "【右：舞依／即答】", "text": "違います" },
                { "id": "scene2-037", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-038", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海／普通】", "text": "今はね" },
                { "id": "scene2-039", "speaker": "mai", "position": "right", "expression": "serious", "direction": "【右：舞依／真顔】", "text": "余計なこと言わないでください" },
                { "id": "scene2-040", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／少し笑う】", "text": "冗談だよ" },
                { "id": "scene2-041", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【左：栞那／少し笑う】", "text": "仲いいじゃん" },
                { "id": "scene2-042", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "同じ学校で、同じ部活だったので" },
                { "id": "scene2-043", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【栞那】", "text": "何部？" },
                { "id": "scene2-044", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "弓道部です" },
                { "id": "scene2-045", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【舞依】", "text": "私が入ったとき、拓海先輩が教育係でした" },
                { "id": "scene2-046", "speaker": "narration", "text": "", "hide": [ "mai" ], "direction": "【舞依・消える】" },
                { "id": "scene2-047", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "最初はかなり危なっかしかったけどね" },
                { "id": "scene2-048", "speaker": "mai", "position": "right", "expression": "pout", "direction": "【右：舞依／少し不満】", "text": "余計です" },
                { "id": "scene2-049", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "でも覚えるの早かったよ" },
                { "id": "scene2-050", "speaker": "mai", "position": "right", "expression": "smile", "direction": "【右：舞依】", "text": "それなら許します" },
                { "id": "scene2-051", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑顔】", "text": "やっぱり仲いいね" }
            ]
        },
        {
            "id": "scene3",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene3-001", "speaker": "narration", "text": "", "direction": "奥から千鶴がやってくる。" },
                { "id": "scene3-002", "speaker": "chizuru", "position": "left", "expression": "flustered", "direction": "【左：千鶴／少し焦り】", "text": "栞那！",
                "motion": "slideIn",
                "se": "swish" },
                { "id": "scene3-003", "speaker": "chizuru", "position": "left", "expression": "flustered", "direction": "【千鶴】", "text": "探した！",
                "mark": "!" },
                { "id": "scene3-004", "speaker": "narration", "text": "", "hide": [ "chizuru" ], "direction": "【千鶴・消える】" },
                { "id": "scene3-005", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "pose": "pocket", "text": "どうしたの？" },
                { "id": "scene3-006", "speaker": "chizuru", "position": "left", "expression": "flustered", "direction": "【左：千鶴】", "text": "裏で栞那がサボってるって言われてる" },
                { "id": "scene3-007", "speaker": "kanna", "position": "left", "expression": "surprised", "direction": "【栞那／少し驚く】", "text": "え、ひどくない？",
                "motion": "hop",
                "mark": "!",
                "se": "pop" },
                { "id": "scene3-008", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【千鶴／通常】", "text": "だからちゃんと働いてるって言っといた" },
                { "id": "scene3-009", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【千鶴】", "text": "ほら、戻るよ！",
                "mark": "!" },
                { "id": "scene3-010", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／薄い笑顔】", "text": "迎えに来てくれたの？" },
                { "id": "scene3-011", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴／少し嫌そう】", "text": "違う" },
                { "id": "scene3-012", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那】", "text": "優しい後輩だなあ" },
                { "id": "scene3-013", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "置いてくよ！",
                "motion": "zoom",
                "mark": "!" },
                { "id": "scene3-014", "speaker": "mai", "position": "right", "expression": "normal", "pose": "behind", "direction": "【右：舞依】", "text": "千鶴ちゃん" },
                { "id": "scene3-015", "speaker": "narration", "text": "", "direction": "千鶴が止まる。" },
                { "id": "scene3-016", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴】", "text": "ん？" },
                { "id": "scene3-017", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "もう行っちゃう？" },
                { "id": "scene3-018", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴】", "text": "うん。まだ料理あるから" },
                { "id": "scene3-019", "speaker": "mai", "position": "right", "expression": "sad", "direction": "【右：舞依／少し残念そう】", "text": "……そっか" },
                { "id": "scene3-020", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【千鶴】", "text": "どうしたの？" },
                { "id": "scene3-021", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "連絡先、交換しない？" },
                { "id": "scene3-022", "speaker": "chizuru", "position": "left", "expression": "surprised", "direction": "【左：千鶴／少し驚く】", "text": "私と？",
                "motion": "hop",
                "mark": "!?",
                "se": "pop" },
                { "id": "scene3-023", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "うん" },
                { "id": "scene3-024", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／笑顔】", "text": "いいよ！",
                "mark": "!" },
                { "id": "scene3-025", "speaker": "narration", "text": "", "direction": "連絡先交換のSE。", "se": "notify", "wait": 350 },
                { "id": "scene3-026", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【右：舞依／嬉しそう】", "text": "やった！",
                "motion": "hop",
                "mark": "sparkle",
                "se": "sparkle" },
                { "id": "scene3-027", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／千鶴を見る】", "text": "千鶴、ほんと断らないよね" },
                { "id": "scene3-028", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "pose": "behind", "text": "嫌じゃないし" },
                { "id": "scene3-029", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／笑顔】", "text": "そういうところ" }
            ]
        },
        {
            "id": "scene4",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene4-001", "speaker": "narration", "text": "", "direction": "舞依が少し考える。" },
                { "id": "scene4-002", "speaker": "mai", "position": "right", "expression": "happy", "pose": "behind", "direction": "【右：舞依】", "text": "千鶴ちゃん" },
                { "id": "scene4-003", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "私も料理、手伝っていい？" },
                { "id": "scene4-004", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／即答】", "text": "それはさすがにダメ" },
                { "id": "scene4-005", "speaker": "mai", "position": "right", "expression": "pout", "pose": "default", "direction": "【右：舞依／少し不満】", "text": "なんでですか" },
                { "id": "scene4-006", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "text": "他校の生徒だし" },
                { "id": "scene4-007", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "text": "先生に見つかったら説明面倒だよ" },
                { "id": "scene4-008", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴／普通】", "text": "先生に内緒なら大丈夫じゃない？" },
                { "id": "scene4-009", "speaker": "kanna", "position": "left", "expression": "troubled", "direction": "【栞那／困惑】", "text": "千鶴？" },
                { "id": "scene4-010", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【千鶴】", "text": "人手増えるし" },
                { "id": "scene4-011", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴／笑顔】", "pose": "cheer", "text": "楽しそう！",
                "mark": "!" },
                { "id": "scene4-012", "speaker": "kanna", "position": "left", "expression": "troubled", "direction": "【栞那】", "text": "そこ？" },
                { "id": "scene4-013", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／普通に会話へ入る】", "text": "でも、本当に大丈夫？" },
                { "id": "scene4-014", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【拓海】", "text": "僕たち他校の生徒だし、先生に見つかったら千鶴たちが困らない？" },
                { "id": "scene4-015", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "全然" },
                { "id": "scene4-016", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "むしろ楽しいよ！",
                "mark": "!" },
                { "id": "scene4-017", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海】", "text": "千鶴がいいなら僕はいいけど" },
                { "id": "scene4-018", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【右：舞依】", "text": "じゃあ決まりですね" },
                { "id": "scene4-019", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海／舞依を見る】", "text": "舞依は決めるの早いな" },
                { "id": "scene4-020", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "拓海先輩が嫌なら、知り合いのところ行ってきていいですよ" },
                { "id": "scene4-021", "speaker": "takumi", "position": "left", "expression": "troubled", "direction": "【左：拓海】", "text": "いや、僕もいるよ" },
                { "id": "scene4-022", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／少し笑う】", "text": "ここまで来たら手伝ったほうが楽しそうだし" },
                { "id": "scene4-023", "speaker": "mai", "position": "right", "expression": "surprised", "direction": "【右：舞依／少し意外そう】", "text": "珍しく乗り気ですね" },
                { "id": "scene4-024", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海】", "text": "僕だって普通に楽しむよ" },
                { "id": "scene4-025", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "それに舞依だけ置いていったら、あとで何するか分からないし" },
                { "id": "scene4-026", "speaker": "mai", "position": "right", "expression": "serious", "pose": "default", "direction": "【右：舞依／真顔】", "text": "どういう意味ですか" },
                { "id": "scene4-027", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "そのままの意味" },
                { "id": "scene4-028", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "でも先生に見つかったら、本当にどうするの？" },
                { "id": "scene4-029", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "それもそれで楽しそう" },
                { "id": "scene4-030", "speaker": "kanna", "position": "left", "expression": "exasperated", "direction": "【栞那／呆れ】", "pose": "pocket", "text": "怒られるの千鶴だしね" },
                { "id": "scene4-031", "speaker": "chizuru", "position": "left", "expression": "smug", "direction": "【千鶴／得意げ】", "text": "全責任、私が取るよ！",
                "mark": "sparkle",
                "se": "idea" },
                { "id": "scene4-032", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／笑顔】", "text": "その自信どこから来るの" },
                { "id": "scene4-033", "speaker": "chizuru", "position": "left", "expression": "smug", "direction": "【千鶴】", "text": "なんとかなる！",
                "mark": "!" },
                { "id": "scene4-034", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／笑う】", "text": "意外と大胆なんだね" },
                { "id": "scene4-035", "speaker": "mai", "position": "right", "expression": "serious", "direction": "【右：舞依／千鶴を見る】", "text": "……" },
                { "id": "scene4-036", "speaker": "mai", "position": "right", "expression": "gentle", "pose": "behind", "direction": "【右：舞依／柔らかく笑う】", "text": "やっぱり千鶴ちゃん好き",
                "mark": "sparkle" },
                { "id": "scene4-037", "speaker": "chizuru", "position": "left", "expression": "embarrassed", "direction": "【左：千鶴／少し照れる】", "pose": "behind", "text": "また言ってる",
                "mark": "sweat" },
                { "id": "scene4-038", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "何回でも言うよ" },
                { "id": "scene4-039", "speaker": "takumi", "position": "left", "expression": "exasperated", "direction": "【左：拓海／少しだけ呆れる】", "text": "完全にお気に入りだね" },
                { "id": "scene4-040", "speaker": "mai", "position": "right", "expression": "gentle", "direction": "【右：舞依】", "text": "はい" }
            ]
        },
        {
            "id": "scene5",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene5-001", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "pose": "pocket", "text": "じゃあ、その前に一つだけ" },
                { "id": "scene5-002", "speaker": "mai", "position": "right", "expression": "thinking", "direction": "【右：舞依】", "text": "？",
                "mark": "?" },
                { "id": "scene5-003", "speaker": "narration", "text": "", "direction": "栞那がBattle à la carteのカードを手に取る。" },
                { "id": "scene5-004", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【左：栞那／少し挑発的】", "text": "千鶴に勝ったんでしょ？" },
                { "id": "scene5-005", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那】", "text": "私ともやってみる？" },
                { "id": "scene5-006", "speaker": "mai", "position": "right", "expression": "laugh", "direction": "【右：舞依／少し笑う】", "text": "いいですよ" },
                { "id": "scene5-007", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【左：栞那】", "text": "即答なんだ" },
                { "id": "scene5-008", "speaker": "mai", "position": "right", "expression": "laugh", "direction": "【右：舞依】", "text": "女の子からのお誘いは断らないので" },
                { "id": "scene5-009", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／笑う】", "text": "それ、僕が誘った時と反応違いすぎない？" },
                { "id": "scene5-010", "speaker": "mai", "position": "right", "expression": "laugh", "direction": "【右：舞依】", "text": "当たり前です" },
                { "id": "scene5-011", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海】", "text": "即答された" },
                { "id": "battle-start", "speaker": "narration", "text": "", "battle": true, "direction": "BATTLE START" }
            ]
        },
        {
            "id": "win",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "win-001", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【右：舞依／満足そう】", "text": "勝ちました" },
                { "id": "win-002", "speaker": "kanna", "position": "left", "expression": "sad", "direction": "【左：栞那／少し悔しい】", "text": "強いね" },
                { "id": "win-003", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "楽しかったです" },
                { "id": "win-004", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑顔】", "pose": "pocket", "text": "そっか" },
                { "id": "win-005", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那】", "text": "じゃあ負けたし、料理手伝うの許可してあげる" },
                { "id": "win-006", "speaker": "mai", "position": "right", "expression": "happy", "pose": "default", "direction": "【右：舞依】", "text": "勝っても手伝うつもりでしたけど" },
                { "id": "win-007", "speaker": "kanna", "position": "left", "expression": "frozen", "direction": "【左：栞那／一瞬止まる】", "text": "……千鶴",
                "motion": "tremble",
                "mark": "…",
                "se": "shock" },
                { "id": "win-008", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴】", "text": "ん？" },
                { "id": "win-009", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "この子、結構強いね" },
                { "id": "win-010", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴／笑顔】", "text": "いい子でしょ？" },
                { "id": "win-011", "speaker": "kanna", "position": "left", "expression": "exasperated", "direction": "【栞那】", "text": "そういう意味じゃない" },
                { "id": "win-012", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／笑いながら】", "text": "舞依、割と押し強いからね" },
                { "id": "win-013", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "拓海先輩に言われたくないです" },
                { "id": "win-014", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海】", "text": "僕そんなに押し強い？" },
                { "id": "win-015", "speaker": "mai", "position": "right", "expression": "normal", "direction": "【右：舞依】", "text": "たまに" }
            ],
            "next": "scene6"
        },
        {
            "id": "scene6",
            "background": "festival-kitchen",
            "bgm": "story",
            "lines": [
                { "id": "scene6-001", "speaker": "narration", "text": "", "direction": "千鶴、栞那、舞依、拓海が裏の料理スペースへ向かう。" },
                { "id": "scene6-002", "speaker": "mai", "position": "right", "expression": "happy", "pose": "cheer", "direction": "【右：舞依／少し嬉しそう】", "text": "何したらいい？" },
                { "id": "scene6-003", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "じゃあ、簡単なのからお願い" },
                { "id": "scene6-004", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "任せて" },
                { "id": "scene6-005", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "僕は？" },
                { "id": "scene6-006", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "pose": "behind", "text": "拓海も手伝ってくれる？" },
                { "id": "scene6-007", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海／笑顔】", "text": "もちろん" },
                { "id": "scene6-008", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "意外と楽しそうですね" },
                { "id": "scene6-009", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【左：拓海】", "text": "文化祭だしね" },
                { "id": "scene6-010", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／少し笑う】", "text": "舞依について来ただけで終わるのも、ちょっともったいないし" },
                { "id": "scene6-011", "speaker": "mai", "position": "right", "expression": "happy", "direction": "【右：舞依】", "text": "それはそうですね" },
                { "id": "scene6-012", "speaker": "narration", "text": "", "direction": "少し時間が経過する。" },
                { "id": "scene6-013", "speaker": "narration", "text": "", "direction": "何組かの客が料理を楽しんで帰っていく。" },
                { "id": "scene6-014", "speaker": "narration", "text": "", "direction": "教室の外から、遠くに大きな笑い声が聞こえる。" },
                { "id": "scene6-015", "speaker": "narration", "name": "？？？", "offscreen": true, "hide": "all", "text": "いやそれ絶対ちゃうやろ！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines",
                "se": "thud", "direction": "", "effect": "crowd" },
                { "id": "scene6-016", "speaker": "narration", "text": "", "direction": "続いて、さらに大きな男の声。" },
                { "id": "scene6-017", "speaker": "narration", "name": "？？？", "offscreen": true, "hide": "all", "text": "ええやん！結果おもろかったら！",
                "motion": "zoom",
                "mark": "!",
                "screen": "speedLines", "direction": "", "se": "crowd", "effect": "shake" },
                { "id": "scene6-018", "speaker": "mai", "position": "right", "expression": "serious", "pose": "default", "direction": "【右：舞依／真顔】", "text": "……" },
                { "id": "scene6-019", "speaker": "kanna", "position": "left", "expression": "pout", "direction": "【左：栞那／嫌そうな顔】", "pose": "pocket", "text": "なんかうるさいの近づいてきてない？" },
                { "id": "scene6-020", "speaker": "mai", "position": "right", "expression": "serious", "direction": "【右：舞依】", "text": "来てますね" },
                { "id": "scene6-021", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海／入口を見る】", "text": "元気だなあ" },
                { "id": "scene6-022", "speaker": "mai", "position": "right", "expression": "serious", "direction": "【右：舞依】", "text": "声が大きいだけじゃないですか" },
                { "id": "scene6-023", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／少し笑う】", "text": "それもあるかも" },
                { "id": "scene6-024", "speaker": "narration", "text": "", "direction": "声がさらに近くなる。" },
                { "id": "scene6-025", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴／入口を見る】", "pose": "default", "text": "お客さんかな" },
                { "id": "scene6-026", "speaker": "narration", "text": "", "direction": "画面暗転。", "hide": "all", "effect": "fadeOut" }
            ]
        },
        {
            "id": "lose",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "lose-001", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【左：栞那／薄い笑顔】", "pose": "pocket", "text": "私の勝ち" },
                { "id": "lose-002", "speaker": "mai", "position": "right", "expression": "pout", "direction": "【右：舞依／少し不満】", "text": "……もう一回お願いします",
                "motion": "tremble",
                "mark": "sweat" },
                { "id": "lose-003", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑顔】", "text": "いいよ。何回でも" },
                { "id": "lose-004", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【左：拓海／少し笑う】", "text": "舞依、負けず嫌いだからね" }
            ]
        }
    ],
    "battle": {
        "after": "battle-start",
        "player": "mai",
        "cpu": "kanna",
        "playerSkill": "choose",
        "cpuSkill": "random",
        "cpuPersonality": "default"
    },
    "afterBattle": {
        "win": "win",
        "lose": "lose"
    },
    "clear": {
        "title": "もう少し、ここにいたい",
        "next": {
            "number": 7,
            "title": "うるさい二人が来た"
        }
    }
});
