// 台本原本: docs/story/episode8-scenario.md（表示台詞の行末句点だけ除去）
// 敗北会話: docs/story/lose-lines-ep8.md（2026-10-03 オーナー承認済み）
window.BattleStoryData.register({
    "id": "episode8",
    "number": 8,
    "arc": "festival",
    "title": "なんか気になる",
    "protagonist": "akatsuki",
    "unlockRequires": "episode7",
    "summary": "食事を終えても、なぜか席を立たない暁。千鶴をいじる理由は「おもろいから」――本当にそれだけ？",
    "defaultPositions": {
        "chizuru": "left",
        "kanna": "left",
        "mai": "left",
        "takumi": "left",
        "akatsuki": "right",
        "tsuyoshi": "left"
    },
    "scenes": [
        {
            "id": "scene1",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene1-001", "speaker": "narration", "text": "", "direction": "暁と剛は食事を終えている。" },
                { "id": "scene1-002", "speaker": "narration", "text": "", "direction": "剛は満足そうに椅子へもたれ、暁は空になった皿を見ている。" },
                { "id": "scene1-003", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛／満足】", "text": "食った食った！",
                "mark": "sparkle" },
                { "id": "scene1-004", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【剛】", "text": "普通にうまかったな！",
                "mark": "!" },
                { "id": "scene1-005", "speaker": "narration", "text": "", "direction": "【剛・消える】", "hide": ["tsuyoshi"] },
                { "id": "scene1-006", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁／通常】", "text": "普通にってなんやねん" },
                { "id": "scene1-007", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【暁】", "text": "失礼やろ" },
                { "id": "scene1-008", "speaker": "narration", "text": "", "direction": "【暁・消える】", "hide": ["akatsuki"] },
                { "id": "scene1-009", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛】", "text": "褒めてんねん！",
                "mark": "!" },
                { "id": "scene1-010", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "お前の褒め方、ちょいちょい損すんねん" },
                { "id": "scene1-011", "speaker": "narration", "text": "", "direction": "少し離れたところ。" },
                { "id": "scene1-012", "speaker": "narration", "text": "", "direction": "千鶴と栞那が料理の確認をしている。" },
                { "id": "scene1-013", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那／通常】", "pose": "pocket", "text": "千鶴" },
                { "id": "scene1-014", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴】", "text": "なに？" },
                { "id": "scene1-015", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【栞那】", "text": "それ何個目？" },
                { "id": "scene1-016", "speaker": "chizuru", "position": "left", "expression": "frozen", "direction": "【千鶴／少し止まる】", "text": "……何が？",
                "motion": "tremble",
                "mark": "…",
                "se": "shock" },
                { "id": "scene1-017", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／薄い笑顔】", "text": "味見" },
                { "id": "scene1-018", "speaker": "chizuru", "position": "left", "expression": "frozen", "direction": "【千鶴】", "text": "まだ一個" },
                { "id": "scene1-019", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那】", "text": "“まだ”なんだ" },
                { "id": "scene1-020", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴／不満】", "text": "ちゃんと確認してるだけだから" },
                { "id": "scene1-021", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／笑顔】", "text": "じゃあ確認しすぎて、お昼ごはん入らなくなっても知らないよ" },
                { "id": "scene1-022", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "それは困る！",
                "mark": "!" },
                { "id": "scene1-023", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那】", "text": "そこは困るんだ" },
                { "id": "scene1-024", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁／二人を見る】", "text": "……" },
                { "id": "scene1-025", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛】", "text": "どした？" },
                { "id": "scene1-026", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "いや" },
                { "id": "scene1-027", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【暁／少し笑う】", "text": "あいつ、めっちゃいじられてるな思て" },
                { "id": "scene1-028", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛】", "text": "千鶴？" },
                { "id": "scene1-029", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "そう" },
                { "id": "scene1-030", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛】", "text": "仲ええんちゃう？" },
                { "id": "scene1-031", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "まあ、そうなんやろな" }
            ]
        },
        {
            "id": "scene2",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene2-001", "speaker": "narration", "text": "", "direction": "暁と剛がまだ席にいる。" },
                { "id": "scene2-002", "speaker": "narration", "text": "", "direction": "千鶴が近くを通る。" },
                { "id": "scene2-003", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【左：千鶴】", "text": "まだいたんだ" },
                { "id": "scene2-004", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "客に帰れ言うてんの？" },
                { "id": "scene2-005", "speaker": "chizuru", "position": "left", "expression": "flustered", "direction": "【左：千鶴／少し焦る】", "text": "言ってない！",
                "motion": "tremble",
                "mark": "sweat" },
                { "id": "scene2-006", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "顔には書いてたで" },
                { "id": "scene2-007", "speaker": "chizuru", "position": "left", "expression": "flustered", "direction": "【左：千鶴】", "text": "書いてない！",
                "mark": "!" },
                { "id": "scene2-008", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／少し笑う】", "text": "前も同じこと言うてたな" },
                { "id": "scene2-009", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴】", "text": "暁が勝手に言ってるだけでしょ" },
                { "id": "scene2-010", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "せやったっけ" },
                { "id": "scene2-011", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴／むっとする】", "text": "絶対覚えてる！",
                "motion": "shake",
                "mark": "anger",
                "se": "thud" },
                { "id": "scene2-012", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "よう分かったな" },
                { "id": "scene2-013", "speaker": "narration", "text": "", "direction": "少し離れたところから栞那が見る。" },
                { "id": "scene2-014", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑顔】", "pose": "pocket", "text": "千鶴、もう普通にいじられてるね" },
                { "id": "scene2-015", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴／栞那を見る】", "text": "栞那が余計なこと教えるから" },
                { "id": "scene2-016", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那】", "text": "何も教えてないよ" },
                { "id": "scene2-017", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／少し意地悪】", "text": "暁が勝手に気付いたんじゃない？" },
                { "id": "scene2-018", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／少し笑う】", "text": "まあ、分かりやすいからな" },
                { "id": "scene2-019", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴】", "text": "何が？" },
                { "id": "scene2-020", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "反応" },
                { "id": "scene2-021", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴／不満】", "text": "……" },
                { "id": "scene2-022", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "ほら、それ" },
                { "id": "scene2-023", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴】", "text": "やめて！",
                "mark": "!" },
                { "id": "scene2-024", "speaker": "akatsuki", "position": "right", "expression": "happy", "direction": "【右：暁／楽しそう】", "text": "嫌や" },
                { "id": "scene2-025", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴】", "text": "なんで！",
                "mark": "!" },
                { "id": "scene2-026", "speaker": "akatsuki", "position": "right", "expression": "happy", "direction": "【右：暁】", "text": "おもろいから" },
                { "id": "scene2-027", "speaker": "narration", "text": "", "direction": "少し離れたところ。" },
                { "id": "scene2-028", "speaker": "mai", "position": "left", "expression": "pout", "direction": "【左：舞依／千鶴を見る】", "text": "……" },
                { "id": "scene2-029", "speaker": "takumi", "position": "left", "expression": "normal", "direction": "【左：拓海】", "text": "また見てる" },
                { "id": "scene2-030", "speaker": "mai", "position": "left", "expression": "pout", "direction": "【舞依】", "text": "あの人、千鶴ちゃんに馴れ馴れしくないですか" },
                { "id": "scene2-031", "speaker": "takumi", "position": "left", "expression": "laugh", "direction": "【拓海／少し笑う】", "text": "さっき会ったばっかりなのにね" },
                { "id": "scene2-032", "speaker": "mai", "position": "left", "expression": "pout", "direction": "【舞依】", "text": "そういう意味で言ったんじゃないです" },
                { "id": "scene2-033", "speaker": "takumi", "position": "left", "expression": "smile", "direction": "【拓海】", "text": "分かってるよ" }
            ]
        },
        {
            "id": "scene3",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene3-001", "speaker": "narration", "text": "", "direction": "剛が栞那を見る。" },
                { "id": "scene3-002", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛】", "text": "そういや、あんたもBattle à la carteやるん？" },
                { "id": "scene3-003", "speaker": "kanna", "position": "left", "expression": "normal", "direction": "【左：栞那】", "pose": "pocket", "text": "やるよ" },
                { "id": "scene3-004", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛】", "text": "強い？" },
                { "id": "scene3-005", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【栞那／少し笑う】", "text": "どうだろ" },
                { "id": "scene3-006", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "その言い方するやつ大体強いやろ" },
                { "id": "scene3-007", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【栞那】", "text": "じゃあ試してみる？" },
                { "id": "scene3-008", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "俺？" },
                { "id": "scene3-009", "speaker": "kanna", "position": "left", "expression": "laugh", "direction": "【栞那】", "text": "千鶴いじるなら、それくらい付き合ってもらおうかなって" },
                { "id": "scene3-010", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴／反応】", "text": "なんで私基準なの",
                "mark": "?" },
                { "id": "scene3-011", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "知らんがな" },
                { "id": "scene3-012", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／薄い笑顔】", "text": "どうする？" },
                { "id": "scene3-013", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "ええで" },
                { "id": "scene3-014", "speaker": "akatsuki", "position": "right", "expression": "smug", "direction": "【右：暁／少し挑発】", "text": "負けても千鶴に八つ当たりすんなよ" },
                { "id": "scene3-015", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那／笑顔】", "text": "しないよ" },
                { "id": "scene3-016", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那】", "text": "千鶴はいじるだけ" },
                { "id": "scene3-017", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴】", "text": "それもやめて！",
                "motion": "shake",
                "mark": "anger",
                "se": "thud" },
                { "id": "battle-start", "speaker": "narration", "text": "", "battle": true, "direction": "BATTLE START" }
            ]
        },
        {
            "id": "win",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "win-001", "speaker": "akatsuki", "position": "right", "expression": "smug", "direction": "【右：暁／少し得意げ】", "text": "勝ったな" },
                { "id": "win-002", "speaker": "kanna", "position": "left", "expression": "sad", "direction": "【左：栞那／少し悔しそう】", "text": "……強いじゃん" },
                { "id": "win-003", "speaker": "akatsuki", "position": "right", "expression": "smug", "direction": "【右：暁】", "text": "まあな" },
                { "id": "win-004", "speaker": "kanna", "position": "left", "expression": "sad", "direction": "【左：栞那】", "text": "その顔ちょっと腹立つ" },
                { "id": "win-005", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／笑う】", "text": "負けたからやろ" },
                { "id": "win-006", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【左：千鶴／栞那を見る】", "pose": "cheer", "text": "栞那負けた！",
                "mark": "sparkle" },
                { "id": "win-007", "speaker": "kanna", "position": "left", "expression": "exasperated", "direction": "【栞那／千鶴を見る】", "text": "嬉しそうだね" },
                { "id": "win-008", "speaker": "chizuru", "position": "left", "expression": "happy", "direction": "【千鶴】", "text": "ちょっとだけ" },
                { "id": "win-009", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【栞那／意地悪な笑顔】", "pose": "pocket", "text": "じゃああとで覚えててね" },
                { "id": "win-010", "speaker": "chizuru", "position": "left", "expression": "frozen", "direction": "【千鶴／一瞬止まる】", "pose": "default", "text": "やっぱり嬉しくない",
                "motion": "tremble",
                "mark": "…",
                "se": "shock" },
                { "id": "win-011", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／笑う】", "text": "遅いわ" }
            ],
            "next": "scene4"
        },
        {
            "id": "scene4",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene4-001", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【左：剛／暁に近づく】", "text": "勝ったやん！",
                "mark": "!" },
                { "id": "scene4-002", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "見たら分かる" },
                { "id": "scene4-003", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【剛】", "text": "俺もやりたなってきた！",
                "mark": "!" },
                { "id": "scene4-004", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "まずルール覚えろ" },
                { "id": "scene4-005", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【剛】", "text": "教えてや！",
                "mark": "!" },
                { "id": "scene4-006", "speaker": "akatsuki", "position": "right", "expression": "exasperated", "direction": "【右：暁】", "text": "なんで俺やねん" },
                { "id": "scene4-007", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【剛】", "text": "優しいから" },
                { "id": "scene4-008", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "誰がや" },
                { "id": "scene4-009", "speaker": "narration", "text": "", "direction": "千鶴が近くを通る。" },
                { "id": "scene4-010", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "pose": "behind", "text": "剛、私が教えようか？" },
                { "id": "scene4-011", "speaker": "tsuyoshi", "position": "left", "expression": "happy", "direction": "【剛／嬉しそう】", "text": "ほんま？",
                "motion": "hop",
                "mark": "sparkle",
                "se": "sparkle" },
                { "id": "scene4-012", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁／千鶴を見る】", "text": "お前ほんま何でも引き受けるな" },
                { "id": "scene4-013", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【左：千鶴】", "text": "別にいいよ" },
                { "id": "scene4-014", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "忙しいんちゃうん" },
                { "id": "scene4-015", "speaker": "chizuru", "position": "left", "expression": "smile", "direction": "【千鶴】", "text": "今はちょっと落ち着いてるし" },
                { "id": "scene4-016", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "頼まれたら断れへんタイプ？" },
                { "id": "scene4-017", "speaker": "chizuru", "position": "left", "expression": "thinking", "direction": "【左：千鶴／少し考える】", "text": "……そうかも" },
                { "id": "scene4-018", "speaker": "akatsuki", "position": "right", "expression": "smile", "direction": "【右：暁】", "text": "自覚あんねや" },
                { "id": "scene4-019", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【千鶴】", "text": "でも嫌なら断るよ" },
                { "id": "scene4-020", "speaker": "akatsuki", "position": "right", "expression": "smile", "direction": "【右：暁】", "text": "ほんまに？" },
                { "id": "scene4-021", "speaker": "chizuru", "position": "left", "expression": "normal", "direction": "【千鶴】", "text": "……多分" },
                { "id": "scene4-022", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／笑う】", "text": "多分なんや" },
                { "id": "scene4-023", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴／不満】", "pose": "default", "text": "暁、さっきからそればっかり！",
                "mark": "!" },
                { "id": "scene4-024", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "何が？" },
                { "id": "scene4-025", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "私のこといじってる！",
                "mark": "!" },
                { "id": "scene4-026", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "今気付いたん？" },
                { "id": "scene4-027", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "気付いてた！",
                "motion": "shake",
                "mark": "anger",
                "se": "thud" },
                { "id": "scene4-028", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／笑う】", "text": "ほなええやん" },
                { "id": "scene4-029", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "よくない！",
                "motion": "zoom",
                "mark": "!" },
                { "id": "scene4-030", "speaker": "narration", "text": "", "direction": "栞那が二人を見る。" },
                { "id": "scene4-031", "speaker": "kanna", "position": "left", "expression": "happy", "direction": "【左：栞那／少し楽しそう】", "pose": "pocket", "text": "暁、千鶴いじるの上手くなってない？" },
                { "id": "scene4-032", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "上達するもんなん、それ" },
                { "id": "scene4-033", "speaker": "kanna", "position": "left", "expression": "happy", "direction": "【栞那】", "text": "千鶴は分かりやすいから" },
                { "id": "scene4-034", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴／不満】", "text": "二人とも嫌い",
                "motion": "shake",
                "mark": "anger",
                "se": "thud" },
                { "id": "scene4-035", "speaker": "narration", "text": "", "direction": "一瞬の間。", "wait": 800 },
                { "id": "scene4-036", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那／笑顔】", "text": "はいはい" },
                { "id": "scene4-037", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／少し笑う】", "text": "言い方に全然嫌い感ないで" },
                { "id": "scene4-038", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "うるさい！",
                "mark": "!" },
                { "id": "scene4-039", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "はいはい" },
                { "id": "scene4-040", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "それ栞那の真似？" },
                { "id": "scene4-041", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "さあな" }
            ],
            "next": "scene5"
        },
        {
            "id": "scene5",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "scene5-001", "speaker": "narration", "text": "", "direction": "暁と剛はまだ教室にいる。" },
                { "id": "scene5-002", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【左：剛】", "text": "なあ" },
                { "id": "scene5-003", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "なんや" },
                { "id": "scene5-004", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "俺らいつまでおるん？" },
                { "id": "scene5-005", "speaker": "akatsuki", "position": "right", "expression": "thinking", "direction": "【右：暁】", "text": "……" },
                { "id": "scene5-006", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "飯もう食ったで" },
                { "id": "scene5-007", "speaker": "akatsuki", "position": "right", "expression": "normal", "direction": "【右：暁】", "text": "分かってるわ" },
                { "id": "scene5-008", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "ほな行く？" },
                { "id": "scene5-009", "speaker": "akatsuki", "position": "right", "expression": "thinking", "direction": "【右：暁／少し考える】", "text": "……もうちょいええやろ" },
                { "id": "scene5-010", "speaker": "tsuyoshi", "position": "left", "expression": "surprised", "direction": "【剛／少し意外そう】", "text": "珍し" },
                { "id": "scene5-011", "speaker": "akatsuki", "position": "right", "expression": "thinking", "direction": "【右：暁】", "text": "何がや" },
                { "id": "scene5-012", "speaker": "tsuyoshi", "position": "left", "expression": "normal", "direction": "【剛】", "text": "いや別に" },
                { "id": "scene5-013", "speaker": "akatsuki", "position": "right", "expression": "cold", "direction": "【右：暁／少し睨む】", "text": "言いたいことあるなら言え" },
                { "id": "scene5-014", "speaker": "tsuyoshi", "position": "left", "expression": "laugh", "direction": "【剛／笑う】", "text": "なんもないって！",
                "motion": "hop",
                "mark": "note",
                "se": "laugh" },
                { "id": "scene5-015", "speaker": "narration", "text": "", "direction": "少し離れたところで千鶴がまた何かをつまもうとしている。" },
                { "id": "scene5-016", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【左：栞那】", "pose": "pocket", "text": "千鶴" },
                { "id": "scene5-017", "speaker": "chizuru", "position": "left", "expression": "frozen", "direction": "【左：千鶴／びくっ】", "text": "……なに？",
                "motion": "hop",
                "mark": "!",
                "se": "pop" },
                { "id": "scene5-018", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那】", "text": "手" },
                { "id": "scene5-019", "speaker": "chizuru", "position": "left", "expression": "frozen", "direction": "【千鶴／手を引っ込める】", "text": "まだ食べてない！",
                "mark": "!" },
                { "id": "scene5-020", "speaker": "kanna", "position": "left", "expression": "smile", "direction": "【栞那】", "text": "まだ？" },
                { "id": "scene5-021", "speaker": "chizuru", "position": "left", "expression": "frozen", "direction": "【千鶴】", "text": "……食べない" },
                { "id": "scene5-022", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／思わず笑う】", "text": "ほんま分かりやすいな",
                "mark": "note" },
                { "id": "scene5-023", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【左：千鶴／暁を見る】", "text": "また笑ってる" },
                { "id": "scene5-024", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁】", "text": "おもろいからしゃあない" },
                { "id": "scene5-025", "speaker": "chizuru", "position": "left", "expression": "pout", "direction": "【千鶴】", "text": "私は面白くない" },
                { "id": "scene5-026", "speaker": "akatsuki", "position": "right", "expression": "gentle", "direction": "【右：暁／少し柔らかく】", "text": "俺はおもろい" },
                { "id": "scene5-027", "speaker": "narration", "text": "", "direction": "千鶴がむっとする。", "show": [{"id":"chizuru","position":"left","expression":"pout","onlyIfShown":true}] },
                { "id": "scene5-028", "speaker": "akatsuki", "position": "right", "expression": "laugh", "direction": "【右：暁／小さく笑う】", "text": "……" },
                { "id": "scene5-029", "speaker": "narration", "text": "", "direction": "画面暗転。", "hide": "all", "effect": "fadeOut" }
            ]
        },
        {
            "id": "lose",
            "background": "festival-classroom",
            "bgm": "story",
            "lines": [
                { "id": "lose-001", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【左：栞那／薄い笑顔】", "pose": "pocket", "text": "私の勝ち" },
                { "id": "lose-002", "speaker": "akatsuki", "position": "right", "expression": "sad", "direction": "【右：暁／少し悔しそう】", "text": "……マジか",
                "motion": "tremble",
                "mark": "…",
                "se": "shock" },
                { "id": "lose-003", "speaker": "kanna", "position": "left", "expression": "smug", "direction": "【左：栞那／少し意地悪】", "text": "千鶴をいじってる場合じゃなかったね" },
                { "id": "lose-004", "speaker": "akatsuki", "position": "right", "expression": "smug", "direction": "【右：暁／少し挑発】", "text": "もう一回や。次は勝つ" }
            ]
        }
    ],
    "battle": {
        "after": "battle-start",
        "player": "akatsuki",
        "cpu": "kanna",
        "playerSkill": "choose",
        "cpuSkill": "random",
        "cpuPersonality": "default"
    },
    "afterBattle": {
        "win": "win",
        "lose": "lose"
    },
    "clear": {
        "title": "なんか気になる",
        "next": {
            "number": 9,
            "title": "六人でやれば"
        }
    }
});
