// Generated by node tools/measure-story-icons.cjs; do not edit.
(function(root) {
const data = {
  "version": "20261007-osananajimi105a",
  "sourceSize": 512,
  "method": "reviewed-eye-midpoint + cheek-ink-contour-at-eye-plus-45; normal-reference-shared-overscan",
  "characters": {
    "chizuru": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.4765625
      },
      "targetFaceWidth": 0.37532757391078825,
      "overscan": 1.0443897708821934,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/chizuru-normal.png",
          "sha256": "8b1bd1fd0ee3eb529d5be832c5a2dc857e2a299047e933727147c51c2cc3b59e",
          "eyeCenter": {
            "x": 254,
            "y": 244
          },
          "face": {
            "left": 162,
            "right": 345,
            "y": 289
          },
          "faceWidth": 184,
          "scale": 1.0443897708821934,
          "left": -0.018115237898588155,
          "top": -0.02115450018604531
        },
        "smile": {
          "source": "assets/images/story/icons/chizuru-smile.png",
          "sha256": "768311f082fa183c1d28b4c2d02b9fc9b65210496300677ddaa45f57d7faa3fe",
          "eyeCenter": {
            "x": 254,
            "y": 243
          },
          "face": {
            "left": 161,
            "right": 345,
            "y": 288
          },
          "faceWidth": 185,
          "scale": 1.0387444207693168,
          "left": -0.015314614991028264,
          "top": -0.016435340326062475
        },
        "troubled": {
          "source": "assets/images/story/icons/chizuru-troubled.png",
          "sha256": "9fd8bf9219b42d712a9f1b528929bdec2f3f7875815e7e6511e9bb10bf107f7f",
          "eyeCenter": {
            "x": 255,
            "y": 244
          },
          "face": {
            "left": 163,
            "right": 347,
            "y": 289
          },
          "faceWidth": 185,
          "scale": 1.0387444207693168,
          "left": -0.01734341268784334,
          "top": -0.018464138022877552
        },
        "surprised": {
          "source": "assets/images/story/icons/chizuru-surprised.png",
          "sha256": "671e73ac671f6f5cd75006365d308e951c81d80d07141024bc46ffe028513080",
          "eyeCenter": {
            "x": 255,
            "y": 245
          },
          "face": {
            "left": 163,
            "right": 345,
            "y": 290
          },
          "faceWidth": 183,
          "scale": 1.0500968188105115,
          "left": -0.022997439056016478,
          "top": -0.025925235563623694
        },
        "gentle": {
          "source": "assets/images/story/icons/chizuru-gentle.png",
          "sha256": "6a003fe7daeb5fb946950596c544859f351e2b461c360a16954c89030db378dc",
          "eyeCenter": {
            "x": 254,
            "y": 241
          },
          "face": {
            "left": 161,
            "right": 346,
            "y": 286
          },
          "faceWidth": 186,
          "scale": 1.0331597733458258,
          "left": -0.012544106308280734,
          "top": -0.009749033938171892
        },
        "laugh": {
          "source": "assets/images/story/icons/chizuru-laugh.png",
          "sha256": "82465a4249cd8e964e70ac0632df6257a583b2fd85cc910e7e21ef76061f89de",
          "eyeCenter": {
            "x": 255,
            "y": 241
          },
          "face": {
            "left": 160,
            "right": 346,
            "y": 286
          },
          "faceWidth": 187,
          "scale": 1.027634854771784,
          "left": -0.011810328060165798,
          "top": -0.007148437499999882
        }
      }
    },
    "mai": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.494140625
      },
      "targetFaceWidth": 0.43148678414096914,
      "overscan": 1.1387692447431763,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/mai-normal.png",
          "sha256": "5085ecc7dc9f86d20d87f6d1481601cc3ef0766340eb0fd9d70a91d61db7e213",
          "eyeCenter": {
            "x": 283,
            "y": 253
          },
          "face": {
            "left": 188,
            "right": 381,
            "y": 298
          },
          "faceWidth": 194,
          "scale": 1.1387692447431763,
          "left": -0.12943690676234154,
          "top": -0.06857152132817113
        },
        "smile": {
          "source": "assets/images/story/icons/mai-smile.png",
          "sha256": "2708c6ddab9a7f6ee20e3f1126eadca01be7e572bfe22788e7e27e91512b23f1",
          "eyeCenter": {
            "x": 255,
            "y": 252
          },
          "face": {
            "left": 159,
            "right": 352,
            "y": 297
          },
          "faceWidth": 194,
          "scale": 1.1387692447431763,
          "left": -0.06716046369044915,
          "top": -0.06634736264703212
        },
        "troubled": {
          "source": "assets/images/story/icons/mai-troubled.png",
          "sha256": "e6aeee1f40d4b577baeed16666be55f6d1f6cadf406ec4368357529407c0e036",
          "eyeCenter": {
            "x": 227,
            "y": 253
          },
          "face": {
            "left": 131,
            "right": 323,
            "y": 298
          },
          "faceWidth": 193,
          "scale": 1.144669603524229,
          "left": -0.007499999999999951,
          "top": -0.07148712830396475
        },
        "surprised": {
          "source": "assets/images/story/icons/mai-surprised.png",
          "sha256": "006939b7e7df31675374aacebe983f93bf111ed937b487894bf85a7fb5206701",
          "eyeCenter": {
            "x": 283,
            "y": 249
          },
          "face": {
            "left": 190,
            "right": 379,
            "y": 294
          },
          "faceWidth": 190,
          "scale": 1.1627433341061906,
          "left": -0.14268821006260146,
          "top": -0.07133416053211217
        },
        "gentle": {
          "source": "assets/images/story/icons/mai-gentle.png",
          "sha256": "57d7f86e63a8666db958ef7b85734e5d81a13ca53c6f7af0a1516afd9465d1c4",
          "eyeCenter": {
            "x": 255,
            "y": 247
          },
          "face": {
            "left": 159,
            "right": 350,
            "y": 292
          },
          "faceWidth": 192,
          "scale": 1.150631424375918,
          "left": -0.0730683851872247,
          "top": -0.060949144181351
        },
        "laugh": {
          "source": "assets/images/story/icons/mai-laugh.png",
          "sha256": "e3606a9cf745dc2df80844ce11cfb3631f3bb24f757e835525e7175bb540bf6c",
          "eyeCenter": {
            "x": 226,
            "y": 247
          },
          "face": {
            "left": 131,
            "right": 322,
            "y": 292
          },
          "faceWidth": 192,
          "scale": 1.150631424375918,
          "left": -0.0078959021659325,
          "top": -0.060949144181351
        }
      }
    },
    "takumi": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.5
      },
      "targetFaceWidth": 0.38117903930131,
      "overscan": 1.1548146042737912,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/takumi-normal.png",
          "sha256": "10711804dcb50a1804e31a7b90eb4580b60387064e03a544f8606b0ab9389100",
          "eyeCenter": {
            "x": 283,
            "y": 256
          },
          "face": {
            "left": 196,
            "right": 364,
            "y": 301
          },
          "faceWidth": 169,
          "scale": 1.1548146042737912,
          "left": -0.13830572853414635,
          "top": -0.07740730213689562
        },
        "smile": {
          "source": "assets/images/story/icons/takumi-smile.png",
          "sha256": "d2508c74e25df67685bb4b96ed1c84f09962aad3b3af4aeae1e08c8eaa847bb9",
          "eyeCenter": {
            "x": 256,
            "y": 255
          },
          "face": {
            "left": 170,
            "right": 340,
            "y": 300
          },
          "faceWidth": 171,
          "scale": 1.1413080007150334,
          "left": -0.07065400035751668,
          "top": -0.06842488316862017
        },
        "troubled": {
          "source": "assets/images/story/icons/takumi-troubled.png",
          "sha256": "369eb7b1061e7e8b3ee5bdae8006d8cf582998fe1a734704f9c7abf47aaa9c14",
          "eyeCenter": {
            "x": 241,
            "y": 256
          },
          "face": {
            "left": 153,
            "right": 326,
            "y": 301
          },
          "faceWidth": 174,
          "scale": 1.1216302765647743,
          "left": -0.02795487627365356,
          "top": -0.06081513828238716
        },
        "surprised": {
          "source": "assets/images/story/icons/takumi-surprised.png",
          "sha256": "017dc4a81716bc63050154c2514eb212da73108d4e17795d3ee6028835254e74",
          "eyeCenter": {
            "x": 283,
            "y": 250
          },
          "face": {
            "left": 195,
            "right": 366,
            "y": 295
          },
          "faceWidth": 172,
          "scale": 1.1346724890829694,
          "left": -0.1271724890829694,
          "top": -0.05403930131004364
        },
        "gentle": {
          "source": "assets/images/story/icons/takumi-gentle.png",
          "sha256": "68989e80c26d93e68d2abe9c4ee2c6de5cfd637bc4964beafefe53455ef51889",
          "eyeCenter": {
            "x": 256,
            "y": 249
          },
          "face": {
            "left": 169,
            "right": 341,
            "y": 294
          },
          "faceWidth": 173,
          "scale": 1.128113688568039,
          "left": -0.06405684428401948,
          "top": -0.04863341494812834
        },
        "laugh": {
          "source": "assets/images/story/icons/takumi-laugh.png",
          "sha256": "63bfb2ad36ab79eea04dd41087f356ec528dfe122d3dc7a855c6e830825ebb31",
          "eyeCenter": {
            "x": 241,
            "y": 249
          },
          "face": {
            "left": 151,
            "right": 327,
            "y": 294
          },
          "faceWidth": 177,
          "scale": 1.102619593911134,
          "left": -0.019006488540201816,
          "top": -0.036234919695063206
        }
      }
    },
    "akatsuki": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.484375
      },
      "targetFaceWidth": 0.39235294117647057,
      "overscan": 1.1037621202327084,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/akatsuki-normal.png",
          "sha256": "6ef51305670c9f87486a25775ecb8dc63cb4beca1c59e81c033745cfa953a0b7",
          "eyeCenter": {
            "x": 275,
            "y": 248
          },
          "face": {
            "left": 183,
            "right": 364,
            "y": 293
          },
          "faceWidth": 182,
          "scale": 1.1037621202327084,
          "left": -0.09284098254686479,
          "top": -0.05025977698771811
        },
        "smile": {
          "source": "assets/images/story/icons/akatsuki-smile.png",
          "sha256": "0a6fc39b29587d8e4cf9dd0676f6bc6876cf26d46d638653f3dc5cf30c64ccc8",
          "eyeCenter": {
            "x": 252,
            "y": 247
          },
          "face": {
            "left": 160,
            "right": 343,
            "y": 292
          },
          "faceWidth": 184,
          "scale": 1.0917647058823527,
          "left": -0.03735294117647048,
          "top": -0.04231617647058816
        },
        "troubled": {
          "source": "assets/images/story/icons/akatsuki-troubled.png",
          "sha256": "fb7eddcc302971aeba5f11bb5e476a341bcdc0cac957f302c3f49ead88a5f201",
          "eyeCenter": {
            "x": 239,
            "y": 249
          },
          "face": {
            "left": 149,
            "right": 329,
            "y": 294
          },
          "faceWidth": 181,
          "scale": 1.1098602534936626,
          "left": -0.018079298017549483,
          "top": -0.055381256093597564
        },
        "surprised": {
          "source": "assets/images/story/icons/akatsuki-surprised.png",
          "sha256": "9b614953dfa9a8d872451c43dda02c1be101bc0e253923fd9d446fdcd76639f3",
          "eyeCenter": {
            "x": 274,
            "y": 240
          },
          "face": {
            "left": 181,
            "right": 364,
            "y": 285
          },
          "faceWidth": 184,
          "scale": 1.0917647058823527,
          "left": -0.0842647058823528,
          "top": -0.0273897058823529
        },
        "gentle": {
          "source": "assets/images/story/icons/akatsuki-gentle.png",
          "sha256": "91ee646761077041a29e82bd79af6537fc327254e78a0b7cd2c51575ac5d44cc",
          "eyeCenter": {
            "x": 253,
            "y": 241
          },
          "face": {
            "left": 160,
            "right": 342,
            "y": 286
          },
          "faceWidth": 183,
          "scale": 1.0977306332369012,
          "left": -0.0424333011893282,
          "top": -0.03233023947283831
        },
        "laugh": {
          "source": "assets/images/story/icons/akatsuki-laugh.png",
          "sha256": "6e467304521e08cd215b8f89f04c4aae63372e62b2a01202f19e0b8330a08d61",
          "eyeCenter": {
            "x": 240,
            "y": 241
          },
          "face": {
            "left": 147,
            "right": 329,
            "y": 286
          },
          "faceWidth": 183,
          "scale": 1.0977306332369012,
          "left": -0.014561234329797501,
          "top": -0.03233023947283831
        }
      }
    },
    "kanna": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.50390625
      },
      "targetFaceWidth": 0.3369467213114754,
      "overscan": 1.0782295081967213,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/kanna-normal.png",
          "sha256": "c3acaf60dc8b7c46be84f402a86e416423a7bba17e663425f26a67030786a896",
          "eyeCenter": {
            "x": 266,
            "y": 258
          },
          "face": {
            "left": 184,
            "right": 343,
            "y": 303
          },
          "faceWidth": 160,
          "scale": 1.0782295081967213,
          "left": -0.060173924180327854,
          "top": -0.039420338114754094
        },
        "smile": {
          "source": "assets/images/story/icons/kanna-smile.png",
          "sha256": "f8c0c87aadc6e70cf92518d7381096ad77da4f825f015408c5ee4be449c1ca03",
          "eyeCenter": {
            "x": 266,
            "y": 259
          },
          "face": {
            "left": 184,
            "right": 343,
            "y": 304
          },
          "faceWidth": 160,
          "scale": 1.0782295081967213,
          "left": -0.060173924180327854,
          "top": -0.04152625512295083
        },
        "troubled": {
          "source": "assets/images/story/icons/kanna-troubled.png",
          "sha256": "0b39b1be1f8e57ae906c1b0f90d86fd330ab430c51834b321e92c8429672e028",
          "eyeCenter": {
            "x": 268,
            "y": 257
          },
          "face": {
            "left": 185,
            "right": 346,
            "y": 302
          },
          "faceWidth": 162,
          "scale": 1.0649180327868852,
          "left": -0.05741803278688529,
          "top": -0.030632684426229462
        },
        "surprised": {
          "source": "assets/images/story/icons/kanna-surprised.png",
          "sha256": "b79e3aee8be3274a53ce842dcab00473989f7a28e0db8f4ecfa7688f41ea9ec5",
          "eyeCenter": {
            "x": 265,
            "y": 247
          },
          "face": {
            "left": 182,
            "right": 342,
            "y": 292
          },
          "faceWidth": 161,
          "scale": 1.0715324305060583,
          "left": -0.0546017462580185,
          "top": -0.013024434248039785
        },
        "gentle": {
          "source": "assets/images/story/icons/kanna-gentle.png",
          "sha256": "5865c4c11dfde99976578ccb8185e8466528eed5f3c9825d216b7d6faa25a655",
          "eyeCenter": {
            "x": 265,
            "y": 249
          },
          "face": {
            "left": 183,
            "right": 341,
            "y": 294
          },
          "faceWidth": 159,
          "scale": 1.0850108258583357,
          "left": -0.06157786885245897,
          "top": -0.023765030544385946
        },
        "laugh": {
          "source": "assets/images/story/icons/kanna-laugh.png",
          "sha256": "773800c3aefecbfa7504176e49698429edde77cd7b339faf9446c1121d7ea46f",
          "eyeCenter": {
            "x": 266,
            "y": 249
          },
          "face": {
            "left": 184,
            "right": 343,
            "y": 294
          },
          "faceWidth": 160,
          "scale": 1.0782295081967213,
          "left": -0.060173924180327854,
          "top": -0.0204670850409836
        }
      }
    },
    "tsuyoshi": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.494140625
      },
      "targetFaceWidth": 0.3921605742026749,
      "overscan": 1.0403430776775624,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/tsuyoshi-normal.png",
          "sha256": "06fdc00b584b8cfd7f3cde3c0ed78b11ac092ac2a4d9dec331b55ad0ff23e1c4",
          "eyeCenter": {
            "x": 251,
            "y": 253
          },
          "face": {
            "left": 165,
            "right": 357,
            "y": 298
          },
          "faceWidth": 193,
          "scale": 1.0403430776775624,
          "left": -0.010011938470836257,
          "top": -0.019935153618014234
        },
        "smile": {
          "source": "assets/images/story/icons/tsuyoshi-smile.png",
          "sha256": "e0b60dfe78376581710a5a5107a816cd0ad24590fc56baf5c65ac74bc3cb4466",
          "eyeCenter": {
            "x": 252,
            "y": 253
          },
          "face": {
            "left": 165,
            "right": 351,
            "y": 298
          },
          "faceWidth": 187,
          "scale": 1.0737230694747033,
          "left": -0.028473073257080483,
          "top": -0.03642956362714833
        },
        "troubled": {
          "source": "assets/images/story/icons/tsuyoshi-troubled.png",
          "sha256": "37c4081ab71893faf9a2e0a4de1f3947f1777d0b766f0e1fcd45c014dd3c8333",
          "eyeCenter": {
            "x": 252,
            "y": 253
          },
          "face": {
            "left": 165,
            "right": 357,
            "y": 298
          },
          "faceWidth": 193,
          "scale": 1.0403430776775624,
          "left": -0.012043858544425246,
          "top": -0.019935153618014234
        },
        "surprised": {
          "source": "assets/images/story/icons/tsuyoshi-surprised.png",
          "sha256": "bedfe5e3fd152b5e7a90f22a932a2acd89c346b08cccb6f7d7f48c4ffb1eb3c4",
          "eyeCenter": {
            "x": 251,
            "y": 243
          },
          "face": {
            "left": 163,
            "right": 352,
            "y": 288
          },
          "faceWidth": 190,
          "scale": 1.0567695473251029,
          "left": -0.018064758551954774,
          "top": -0.007412109375000031
        },
        "gentle": {
          "source": "assets/images/story/icons/tsuyoshi-gentle.png",
          "sha256": "b71d5a0c3e367b594a482e99cc9eb94cfe6a94d37891943f2b95d8522bc6a7c7",
          "eyeCenter": {
            "x": 251,
            "y": 246
          },
          "face": {
            "left": 164,
            "right": 353,
            "y": 291
          },
          "faceWidth": 190,
          "scale": 1.0567695473251029,
          "left": -0.018064758551954774,
          "top": -0.013604118441358004
        },
        "laugh": {
          "source": "assets/images/story/icons/tsuyoshi-laugh.png",
          "sha256": "7cf06c644e2a78ab89deead3c1bb493c5047caa8e60031134018ba31054fb387",
          "eyeCenter": {
            "x": 251,
            "y": 246
          },
          "face": {
            "left": 164,
            "right": 353,
            "y": 291
          },
          "faceWidth": 190,
          "scale": 1.0567695473251029,
          "left": -0.018064758551954774,
          "top": -0.013604118441358004
        }
      }
    },
    "yuzuki": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.478515625
      },
      "targetFaceWidth": 0.42363347457627115,
      "overscan": 1.1010169491525423,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/yuzuki-normal.png",
          "sha256": "23352f376e43e493f30627e2213cd8f3be2e8287325cf7139a534ace6045f9ff",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 167,
            "right": 363,
            "y": 290
          },
          "faceWidth": 197,
          "scale": 1.1010169491525423,
          "left": -0.09351694915254238,
          "top": -0.04833818855932204
        },
        "smile": {
          "source": "assets/images/story/icons/yuzuki-smile.png",
          "sha256": "7841d425ec80e02cf12be05088fb5642d2ac44baa7962577c01cc0c568d22df1",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 184,
            "right": 363,
            "y": 290
          },
          "faceWidth": 180,
          "scale": 1.2050018832391713,
          "left": -0.1495713276836158,
          "top": -0.09809660428436906
        },
        "troubled": {
          "source": "assets/images/story/icons/yuzuki-troubled.png",
          "sha256": "05c829e2656e071a22a5d40b4d6f28e67ed33aa311f0584af9d68b7aa5791ec5",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 167,
            "right": 363,
            "y": 290
          },
          "faceWidth": 197,
          "scale": 1.1010169491525423,
          "left": -0.09351694915254238,
          "top": -0.04833818855932204
        },
        "surprised": {
          "source": "assets/images/story/icons/yuzuki-surprised.png",
          "sha256": "a2e98bd381ad792f2f8b2e127b4b4ededfe70df26db6c33e084a99ea1607f981",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 185,
            "right": 363,
            "y": 290
          },
          "faceWidth": 179,
          "scale": 1.2117337373354795,
          "left": -0.1532002177824069,
          "top": -0.1013179016546728
        },
        "gentle": {
          "source": "assets/images/story/icons/yuzuki-gentle.png",
          "sha256": "89cea2b854d9f622341750aa825d7ffbf451002fd1ca3a7bad8170275c9e5bd0",
          "eyeCenter": {
            "x": 276,
            "y": 252
          },
          "face": {
            "left": 185,
            "right": 360,
            "y": 297
          },
          "faceWidth": 176,
          "scale": 1.2323882896764253,
          "left": -0.164334312403698,
          "top": -0.12805048632511562
        },
        "laugh": {
          "source": "assets/images/story/icons/yuzuki-laugh.png",
          "sha256": "89ca480600d78ae61ec06fcf545fb5e519ccda4b5aecf855ba816036bac5aa4f",
          "eyeCenter": {
            "x": 276,
            "y": 250
          },
          "face": {
            "left": 185,
            "right": 361,
            "y": 295
          },
          "faceWidth": 177,
          "scale": 1.2254256439720388,
          "left": -0.16058101120367718,
          "top": -0.1198367402207221
        }
      }
    },
    "ryuta": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.419921875
      },
      "targetFaceWidth": 0.435902489626556,
      "overscan": 1.078174273858921,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/ryuta-normal.png",
          "sha256": "f8ab8caae0083d2f1a8584d34ef8dd13ca77ee3e91328c2dd64bbe32954529d4",
          "eyeCenter": {
            "x": 271,
            "y": 215
          },
          "face": {
            "left": 156,
            "right": 362,
            "y": 260
          },
          "faceWidth": 207,
          "scale": 1.078174273858921,
          "left": -0.07067427385892111,
          "top": -0.032827087655601606
        },
        "smile": {
          "source": "assets/images/story/icons/ryuta-smile.png",
          "sha256": "a0e8b64786d466142b78669d602aadd160f18e21400e840f0df79f48a28c16f2",
          "eyeCenter": {
            "x": 270,
            "y": 215
          },
          "face": {
            "left": 154,
            "right": 360,
            "y": 260
          },
          "faceWidth": 207,
          "scale": 1.078174273858921,
          "left": -0.06856846473029043,
          "top": -0.032827087655601606
        },
        "troubled": {
          "source": "assets/images/story/icons/ryuta-troubled.png",
          "sha256": "57c6e4b3b46235b66c19305808b7efde318841dbcb01dcea2d87bb28750a4972",
          "eyeCenter": {
            "x": 271,
            "y": 216
          },
          "face": {
            "left": 184,
            "right": 361,
            "y": 261
          },
          "faceWidth": 178,
          "scale": 1.2538318802741386,
          "left": -0.16364929600447575,
          "top": -0.10903844949065222
        },
        "surprised": {
          "source": "assets/images/story/icons/ryuta-surprised.png",
          "sha256": "06d9841e2e7092ca27f80be3bf8be5bcd77183a610ebfea31cd6637140aa0424",
          "eyeCenter": {
            "x": 271,
            "y": 213
          },
          "face": {
            "left": 156,
            "right": 362,
            "y": 258
          },
          "faceWidth": 207,
          "scale": 1.078174273858921,
          "left": -0.07067427385892111,
          "top": -0.0286154693983402
        },
        "gentle": {
          "source": "assets/images/story/icons/ryuta-gentle.png",
          "sha256": "7777c6646f6ff92d80674ae116afcae0414f624e23ce6013abb2bb9ded5eb941",
          "eyeCenter": {
            "x": 270,
            "y": 217
          },
          "face": {
            "left": 184,
            "right": 360,
            "y": 262
          },
          "faceWidth": 177,
          "scale": 1.2609156762078908,
          "left": -0.16493600112525486,
          "top": -0.11448965183029747
        },
        "laugh": {
          "source": "assets/images/story/icons/ryuta-laugh.png",
          "sha256": "cb933149062045409b81e8cf38c796ea1e25a71e3110c0668d32a6e565ff21f4",
          "eyeCenter": {
            "x": 270,
            "y": 217
          },
          "face": {
            "left": 155,
            "right": 360,
            "y": 262
          },
          "faceWidth": 206,
          "scale": 1.0834081295572653,
          "left": -0.07132850582121408,
          "top": -0.039256961160012815
        }
      }
    },
    "yuzuki-kyudo": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.478515625
      },
      "targetFaceWidth": 0.42363347457627115,
      "overscan": 1.1010169491525423,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/yuzuki-kyudo-normal.png",
          "sha256": "84c6fa59f2ba845c86a6e45874b1284f15255238ef74c9fbf9ff53006f767844",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 167,
            "right": 363,
            "y": 290
          },
          "faceWidth": 197,
          "scale": 1.1010169491525423,
          "left": -0.09351694915254238,
          "top": -0.04833818855932204
        },
        "smile": {
          "source": "assets/images/story/icons/yuzuki-kyudo-smile.png",
          "sha256": "1836c5cc03c10ff8e9ebe1ae74969a84933598a866fa36bca38a1a0020713567",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 184,
            "right": 363,
            "y": 290
          },
          "faceWidth": 180,
          "scale": 1.2050018832391713,
          "left": -0.1495713276836158,
          "top": -0.09809660428436906
        },
        "troubled": {
          "source": "assets/images/story/icons/yuzuki-kyudo-troubled.png",
          "sha256": "febf97e3d68caa6adeb2ca81952b73a6fef421dd668025a790f87dbf8b497425",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 167,
            "right": 363,
            "y": 290
          },
          "faceWidth": 197,
          "scale": 1.1010169491525423,
          "left": -0.09351694915254238,
          "top": -0.04833818855932204
        },
        "surprised": {
          "source": "assets/images/story/icons/yuzuki-kyudo-surprised.png",
          "sha256": "d1a912cf0388eff9aa5fd5d4487532c94cf858c37ebb35e2abaac566305a3bb1",
          "eyeCenter": {
            "x": 276,
            "y": 245
          },
          "face": {
            "left": 185,
            "right": 363,
            "y": 290
          },
          "faceWidth": 179,
          "scale": 1.2117337373354795,
          "left": -0.1532002177824069,
          "top": -0.1013179016546728
        },
        "gentle": {
          "source": "assets/images/story/icons/yuzuki-kyudo-gentle.png",
          "sha256": "041425b2328b75b265ac2a68f256ec6880fea795b20ece30fe2fcb2f83832a9a",
          "eyeCenter": {
            "x": 276,
            "y": 252
          },
          "face": {
            "left": 185,
            "right": 360,
            "y": 297
          },
          "faceWidth": 176,
          "scale": 1.2323882896764253,
          "left": -0.164334312403698,
          "top": -0.12805048632511562
        },
        "laugh": {
          "source": "assets/images/story/icons/yuzuki-kyudo-laugh.png",
          "sha256": "a5abdcd9af613889220aa805982ed294a5065758e346b6fa75ff491e306701ba",
          "eyeCenter": {
            "x": 276,
            "y": 250
          },
          "face": {
            "left": 185,
            "right": 361,
            "y": 295
          },
          "faceWidth": 177,
          "scale": 1.2254256439720388,
          "left": -0.16058101120367718,
          "top": -0.1198367402207221
        }
      }
    },
    "takumi-kyudo": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.5
      },
      "targetFaceWidth": 0.38117903930131,
      "overscan": 1.1548146042737912,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/takumi-kyudo-normal.png",
          "sha256": "9f126872ae6589623c6deb639f35aaf7e38b8202d2621507df76c3b3ee737693",
          "eyeCenter": {
            "x": 283,
            "y": 256
          },
          "face": {
            "left": 196,
            "right": 364,
            "y": 301
          },
          "faceWidth": 169,
          "scale": 1.1548146042737912,
          "left": -0.13830572853414635,
          "top": -0.07740730213689562
        },
        "smile": {
          "source": "assets/images/story/icons/takumi-kyudo-smile.png",
          "sha256": "428f77ab2308e206e613c0478142ec56ffaa4a97a93c9e58854bb83528aa796d",
          "eyeCenter": {
            "x": 256,
            "y": 255
          },
          "face": {
            "left": 170,
            "right": 340,
            "y": 300
          },
          "faceWidth": 171,
          "scale": 1.1413080007150334,
          "left": -0.07065400035751668,
          "top": -0.06842488316862017
        },
        "troubled": {
          "source": "assets/images/story/icons/takumi-kyudo-troubled.png",
          "sha256": "2f1dfeffdc1dcf24efca14a6e6f01d842b13a045604dcbe47783dae14fb3cf69",
          "eyeCenter": {
            "x": 241,
            "y": 256
          },
          "face": {
            "left": 153,
            "right": 326,
            "y": 301
          },
          "faceWidth": 174,
          "scale": 1.1216302765647743,
          "left": -0.02795487627365356,
          "top": -0.06081513828238716
        },
        "surprised": {
          "source": "assets/images/story/icons/takumi-kyudo-surprised.png",
          "sha256": "277d1ead15aa75b2f43142b245050cb646004e48454eb1629c2928871acb140a",
          "eyeCenter": {
            "x": 283,
            "y": 250
          },
          "face": {
            "left": 195,
            "right": 366,
            "y": 295
          },
          "faceWidth": 172,
          "scale": 1.1346724890829694,
          "left": -0.1271724890829694,
          "top": -0.05403930131004364
        },
        "gentle": {
          "source": "assets/images/story/icons/takumi-kyudo-gentle.png",
          "sha256": "64560f0d00f954ab9556d1f403830d51242e558d4b3aded4d5fb0fdd19027e32",
          "eyeCenter": {
            "x": 256,
            "y": 249
          },
          "face": {
            "left": 169,
            "right": 341,
            "y": 294
          },
          "faceWidth": 173,
          "scale": 1.128113688568039,
          "left": -0.06405684428401948,
          "top": -0.04863341494812834
        },
        "laugh": {
          "source": "assets/images/story/icons/takumi-kyudo-laugh.png",
          "sha256": "d28871344c595271923fa94d8f2c232e5289e33f7d47043872c8e7aa08c82908",
          "eyeCenter": {
            "x": 241,
            "y": 249
          },
          "face": {
            "left": 151,
            "right": 327,
            "y": 294
          },
          "faceWidth": 177,
          "scale": 1.102619593911134,
          "left": -0.019006488540201816,
          "top": -0.036234919695063206
        }
      }
    },
    "mai-kyudo": {
      "reference": "normal",
      "targetEye": {
        "x": 0.5,
        "y": 0.494140625
      },
      "targetFaceWidth": 0.43148678414096914,
      "overscan": 1.1387692447431763,
      "cells": {
        "normal": {
          "source": "assets/images/story/icons/mai-kyudo-normal.png",
          "sha256": "968a31c5d1f2006561bade7adc0caa836f6b1679f561681944dcf765753a19d1",
          "eyeCenter": {
            "x": 283,
            "y": 253
          },
          "face": {
            "left": 188,
            "right": 381,
            "y": 298
          },
          "faceWidth": 194,
          "scale": 1.1387692447431763,
          "left": -0.12943690676234154,
          "top": -0.06857152132817113
        },
        "smile": {
          "source": "assets/images/story/icons/mai-kyudo-smile.png",
          "sha256": "72565bc938ee034a83fdba6670cda41f047df6b25c8ed7c3f163a2648b9542c3",
          "eyeCenter": {
            "x": 255,
            "y": 252
          },
          "face": {
            "left": 159,
            "right": 352,
            "y": 297
          },
          "faceWidth": 194,
          "scale": 1.1387692447431763,
          "left": -0.06716046369044915,
          "top": -0.06634736264703212
        },
        "troubled": {
          "source": "assets/images/story/icons/mai-kyudo-troubled.png",
          "sha256": "2ce9842dfcdf349bcf83ea74a8e2b779fc79948606764933aa832366b5e2d427",
          "eyeCenter": {
            "x": 227,
            "y": 253
          },
          "face": {
            "left": 131,
            "right": 323,
            "y": 298
          },
          "faceWidth": 193,
          "scale": 1.144669603524229,
          "left": -0.007499999999999951,
          "top": -0.07148712830396475
        },
        "surprised": {
          "source": "assets/images/story/icons/mai-kyudo-surprised.png",
          "sha256": "57e6cca483d6b19f89d9e5f2a504902dc6adafdaa85264965068602c02772330",
          "eyeCenter": {
            "x": 283,
            "y": 249
          },
          "face": {
            "left": 190,
            "right": 379,
            "y": 294
          },
          "faceWidth": 190,
          "scale": 1.1627433341061906,
          "left": -0.14268821006260146,
          "top": -0.07133416053211217
        },
        "gentle": {
          "source": "assets/images/story/icons/mai-kyudo-gentle.png",
          "sha256": "a2fe35aba45e77bbb95bd822aa2839cd02495dda37aaa7ad53b9155f8615a1bc",
          "eyeCenter": {
            "x": 255,
            "y": 247
          },
          "face": {
            "left": 159,
            "right": 350,
            "y": 292
          },
          "faceWidth": 192,
          "scale": 1.150631424375918,
          "left": -0.0730683851872247,
          "top": -0.060949144181351
        },
        "laugh": {
          "source": "assets/images/story/icons/mai-kyudo-laugh.png",
          "sha256": "cb102daf1f9f752f54d44bd4c32dea994ca9e49767d85fcc5e9414307a293dd3",
          "eyeCenter": {
            "x": 226,
            "y": 247
          },
          "face": {
            "left": 131,
            "right": 322,
            "y": 292
          },
          "faceWidth": 192,
          "scale": 1.150631424375918,
          "left": -0.0078959021659325,
          "top": -0.060949144181351
        }
      }
    }
  }
};
data.apply = function(element, id, cell = "normal", costume = "default") {
  const m = (data.characters[id + "-" + costume] || data.characters[id])?.cells[cell]; if (!m) return false;
  Object.assign(element.style, { position: "absolute", inset: "auto", width: (m.scale * 100) + "%", height: "auto", left: (m.left * 100) + "%", top: (m.top * 100) + "%", maxWidth: "none", objectFit: "contain", transform: "none" });
  return true;
};
root.BattleStoryIconMetrics = data;
})(window);
